;; Generated by :claw at 2026-02-05T02:07:35.976415Z
(uiop:define-package :%impeller (:use))
(uiop:define-package :flutter-render-stack-ffi-impeller-bindings~pristine (:use
                                                                           :cl))
(common-lisp:in-package :flutter-render-stack-ffi-impeller-bindings~pristine)

(defparameter %impeller::+export+ nil)

(defparameter %impeller::+export-decoration+ nil)

(defparameter %impeller::+extern-c+ nil)

(defparameter %impeller::+extern-c-begin+ nil)

(defparameter %impeller::+nodiscard+ nil)

(defparameter %impeller::+nonnull+ nil)

(defparameter %impeller::+nullable+ nil)

(defparameter %impeller::+version+ 541081600)

(defparameter %impeller::+version-major+ 1)

(defparameter %impeller::+version-minor+ 4)

(defparameter %impeller::+version-patch+ 0)

(defparameter %impeller::+version-variant+ 1)

(cffi:defbitfield (%impeller::blend-mode :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:374:14"
  :empty)

(cffi:defbitfield (%impeller::blur-style :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:440:14"
  :empty)

(cffi:defbitfield (%impeller::clip-operation :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:369:14"
  :empty)

(cffi:defbitfield (%impeller::color-space :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:447:14"
  :empty)

(cffi:defbitfield (%impeller::draw-style :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:406:14"
  :empty)

(cffi:defbitfield (%impeller::fill-type :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:364:14"
  :empty)

(cffi:defbitfield (%impeller::font-style :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:465:14"
  :empty)

(cffi:defbitfield (%impeller::font-weight :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:453:14"
  :empty)

(cffi:defbitfield (%impeller::pixel-format :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:424:14"
  :empty)

(cffi:defbitfield (%impeller::stroke-cap :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:412:14"
  :empty)

(cffi:defbitfield (%impeller::stroke-join :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:418:14"
  :empty)

(cffi:defbitfield (%impeller::text-alignment :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:470:14"
  :empty)

(cffi:defbitfield (%impeller::text-decoration-style :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:491:14"
  :empty)

(cffi:defbitfield (%impeller::text-decoration-type :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:484:14"
  :empty)

(cffi:defbitfield (%impeller::text-direction :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:479:14"
  :empty)

(cffi:defbitfield (%impeller::texture-sampling :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:428:14"
  :empty)

(cffi:defbitfield (%impeller::tile-mode :unsigned-int)
  "/home/jboehland/work/render-stack-meta/tmp/flutter-render-stack-ffi/src/impeller/lib/impeller.h:433:14"
  :empty)

(cffi:defcstruct (%impeller::color-filter- :size 0))

(cffi:defctype %impeller::color-filter
               (claw-utils:claw-pointer (:struct %impeller::color-filter-)))

(cffi:defcstruct (%impeller::color :size 20))

(cffi:defctype %impeller::color (:struct %impeller::color))

(cffi:defctype %impeller::blend-mode %impeller::blend-mode)

(declaim (inline %impeller::color-filter-create-blend-new))

(cffi:defcfun ("ImpellerColorFilterCreateBlendNew"
               %impeller::color-filter-create-blend-new)
    %impeller::color-filter
  (%impeller::color (claw-utils:claw-pointer %impeller::color))
  (%impeller::blend-mode %impeller::blend-mode))

(cffi:defcstruct (%impeller::color-matrix :size 80))

(cffi:defctype %impeller::color-matrix (:struct %impeller::color-matrix))

(declaim (inline %impeller::color-filter-create-color-matrix-new))

(cffi:defcfun ("ImpellerColorFilterCreateColorMatrixNew"
               %impeller::color-filter-create-color-matrix-new)
    %impeller::color-filter
  (%impeller::color-matrix (claw-utils:claw-pointer %impeller::color-matrix)))

(declaim (inline %impeller::color-filter-release))

(cffi:defcfun ("ImpellerColorFilterRelease" %impeller::color-filter-release)
    :void
  (%impeller::color-filter %impeller::color-filter))

(declaim (inline %impeller::color-filter-retain))

(cffi:defcfun ("ImpellerColorFilterRetain" %impeller::color-filter-retain)
    :void
  (%impeller::color-filter %impeller::color-filter))

(cffi:defcstruct (%impeller::color-source- :size 0))

(cffi:defctype %impeller::color-source
               (claw-utils:claw-pointer (:struct %impeller::color-source-)))

(cffi:defcstruct (%impeller::point :size 8))

(cffi:defctype %impeller::point (:struct %impeller::point))

(cffi:defctype %impeller::uint32-t :unsigned-int)

(cffi:defctype %impeller::tile-mode %impeller::tile-mode)

(cffi:defcstruct (%impeller::matrix :size 64))

(cffi:defctype %impeller::matrix (:struct %impeller::matrix))

(declaim (inline %impeller::color-source-create-conical-gradient-new))

(cffi:defcfun ("ImpellerColorSourceCreateConicalGradientNew"
               %impeller::color-source-create-conical-gradient-new)
    %impeller::color-source
  (%impeller::start-center (claw-utils:claw-pointer %impeller::point))
  (%impeller::start-radius :float)
  (%impeller::end-center (claw-utils:claw-pointer %impeller::point))
  (%impeller::end-radius :float)
  (%impeller::stop-count %impeller::uint32-t)
  (%impeller::colors (claw-utils:claw-pointer %impeller::color))
  (%impeller::stops (claw-utils:claw-pointer :float))
  (%impeller::tile-mode %impeller::tile-mode)
  (%impeller::transformation (claw-utils:claw-pointer %impeller::matrix)))

(cffi:defcstruct (%impeller::context- :size 0))

(cffi:defctype %impeller::context
               (claw-utils:claw-pointer (:struct %impeller::context-)))

(cffi:defcstruct (%impeller::fragment-program- :size 0))

(cffi:defctype %impeller::fragment-program
               (claw-utils:claw-pointer (:struct %impeller::fragment-program-)))

(cffi:defcstruct (%impeller::texture- :size 0))

(cffi:defctype %impeller::texture
               (claw-utils:claw-pointer (:struct %impeller::texture-)))

(cffi:defctype %impeller::uint8-t :unsigned-char)

(cffi:defctype %impeller::size-t :unsigned-long-long)

(declaim (inline %impeller::color-source-create-fragment-program-new))

(cffi:defcfun ("ImpellerColorSourceCreateFragmentProgramNew"
               %impeller::color-source-create-fragment-program-new)
    %impeller::color-source
  (%impeller::context %impeller::context)
  (%impeller::fragment-program %impeller::fragment-program)
  (%impeller::samplers (claw-utils:claw-pointer %impeller::texture))
  (%impeller::samplers-count %impeller::size-t)
  (%impeller::data (claw-utils:claw-pointer %impeller::uint8-t))
  (%impeller::data-bytes-length %impeller::size-t))

(cffi:defctype %impeller::texture-sampling %impeller::texture-sampling)

(declaim (inline %impeller::color-source-create-image-new))

(cffi:defcfun ("ImpellerColorSourceCreateImageNew"
               %impeller::color-source-create-image-new)
    %impeller::color-source
  (%impeller::image %impeller::texture)
  (%impeller::horizontal-tile-mode %impeller::tile-mode)
  (%impeller::vertical-tile-mode %impeller::tile-mode)
  (%impeller::sampling %impeller::texture-sampling)
  (%impeller::transformation (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::color-source-create-linear-gradient-new))

(cffi:defcfun ("ImpellerColorSourceCreateLinearGradientNew"
               %impeller::color-source-create-linear-gradient-new)
    %impeller::color-source
  (%impeller::start-point (claw-utils:claw-pointer %impeller::point))
  (%impeller::end-point (claw-utils:claw-pointer %impeller::point))
  (%impeller::stop-count %impeller::uint32-t)
  (%impeller::colors (claw-utils:claw-pointer %impeller::color))
  (%impeller::stops (claw-utils:claw-pointer :float))
  (%impeller::tile-mode %impeller::tile-mode)
  (%impeller::transformation (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::color-source-create-radial-gradient-new))

(cffi:defcfun ("ImpellerColorSourceCreateRadialGradientNew"
               %impeller::color-source-create-radial-gradient-new)
    %impeller::color-source
  (%impeller::center (claw-utils:claw-pointer %impeller::point))
  (%impeller::radius :float)
  (%impeller::stop-count %impeller::uint32-t)
  (%impeller::colors (claw-utils:claw-pointer %impeller::color))
  (%impeller::stops (claw-utils:claw-pointer :float))
  (%impeller::tile-mode %impeller::tile-mode)
  (%impeller::transformation (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::color-source-create-sweep-gradient-new))

(cffi:defcfun ("ImpellerColorSourceCreateSweepGradientNew"
               %impeller::color-source-create-sweep-gradient-new)
    %impeller::color-source
  (%impeller::center (claw-utils:claw-pointer %impeller::point))
  (%impeller::start :float)
  (%impeller::end :float)
  (%impeller::stop-count %impeller::uint32-t)
  (%impeller::colors (claw-utils:claw-pointer %impeller::color))
  (%impeller::stops (claw-utils:claw-pointer :float))
  (%impeller::tile-mode %impeller::tile-mode)
  (%impeller::transformation (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::color-source-release))

(cffi:defcfun ("ImpellerColorSourceRelease" %impeller::color-source-release)
    :void
  (%impeller::color-source %impeller::color-source))

(declaim (inline %impeller::color-source-retain))

(cffi:defcfun ("ImpellerColorSourceRetain" %impeller::color-source-retain)
    :void
  (%impeller::color-source %impeller::color-source))

(declaim (inline %impeller::context-create-metal-new))

(cffi:defcfun ("ImpellerContextCreateMetalNew"
               %impeller::context-create-metal-new)
    %impeller::context
  (%impeller::version %impeller::uint32-t))

(cffi:defctype %impeller::proc-address-callback (claw-utils:claw-pointer :void))

(declaim (inline %impeller::context-create-open-gles-new))

(cffi:defcfun ("ImpellerContextCreateOpenGLESNew"
               %impeller::context-create-open-gles-new)
    %impeller::context
  (%impeller::version %impeller::uint32-t)
  (%impeller::gl-proc-address-callback %impeller::proc-address-callback)
  (%impeller::gl-proc-address-callback-user-data
   (claw-utils:claw-pointer :void)))

(cffi:defcstruct (%impeller::context-vulkan-settings :size 24))

(cffi:defctype %impeller::context-vulkan-settings
               (:struct %impeller::context-vulkan-settings))

(declaim (inline %impeller::context-create-vulkan-new))

(cffi:defcfun ("ImpellerContextCreateVulkanNew"
               %impeller::context-create-vulkan-new)
    %impeller::context
  (%impeller::version %impeller::uint32-t)
  (%impeller::settings
   (claw-utils:claw-pointer %impeller::context-vulkan-settings)))

(cffi:defcstruct (%impeller::context-vulkan-info :size 32))

(cffi:defctype %impeller::context-vulkan-info
               (:struct %impeller::context-vulkan-info))

(declaim (inline %impeller::context-get-vulkan-info))

(cffi:defcfun ("ImpellerContextGetVulkanInfo"
               %impeller::context-get-vulkan-info)
    :bool
  (%impeller::context %impeller::context)
  (%impeller::out-vulkan-info
   (claw-utils:claw-pointer %impeller::context-vulkan-info)))

(declaim (inline %impeller::context-release))

(cffi:defcfun ("ImpellerContextRelease" %impeller::context-release)
    :void
  (%impeller::context %impeller::context))

(declaim (inline %impeller::context-retain))

(cffi:defcfun ("ImpellerContextRetain" %impeller::context-retain)
    :void
  (%impeller::context %impeller::context))

(cffi:defcstruct (%impeller::display-list-builder- :size 0))

(cffi:defctype %impeller::display-list-builder
               (claw-utils:claw-pointer
                (:struct %impeller::display-list-builder-)))

(cffi:defcstruct (%impeller::rect :size 16))

(cffi:defctype %impeller::rect (:struct %impeller::rect))

(cffi:defctype %impeller::clip-operation %impeller::clip-operation)

(declaim (inline %impeller::display-list-builder-clip-oval))

(cffi:defcfun ("ImpellerDisplayListBuilderClipOval"
               %impeller::display-list-builder-clip-oval)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::oval-bounds (claw-utils:claw-pointer %impeller::rect))
  (%impeller::op %impeller::clip-operation))

(cffi:defcstruct (%impeller::path- :size 0))

(cffi:defctype %impeller::path
               (claw-utils:claw-pointer (:struct %impeller::path-)))

(declaim (inline %impeller::display-list-builder-clip-path))

(cffi:defcfun ("ImpellerDisplayListBuilderClipPath"
               %impeller::display-list-builder-clip-path)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::path %impeller::path)
  (%impeller::op %impeller::clip-operation))

(declaim (inline %impeller::display-list-builder-clip-rect))

(cffi:defcfun ("ImpellerDisplayListBuilderClipRect"
               %impeller::display-list-builder-clip-rect)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::op %impeller::clip-operation))

(cffi:defcstruct (%impeller::rounding-radii :size 32))

(cffi:defctype %impeller::rounding-radii (:struct %impeller::rounding-radii))

(declaim (inline %impeller::display-list-builder-clip-rounded-rect))

(cffi:defcfun ("ImpellerDisplayListBuilderClipRoundedRect"
               %impeller::display-list-builder-clip-rounded-rect)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::radii (claw-utils:claw-pointer %impeller::rounding-radii))
  (%impeller::op %impeller::clip-operation))

(cffi:defcstruct (%impeller::display-list- :size 0))

(cffi:defctype %impeller::display-list
               (claw-utils:claw-pointer (:struct %impeller::display-list-)))

(declaim (inline %impeller::display-list-builder-create-display-list-new))

(cffi:defcfun ("ImpellerDisplayListBuilderCreateDisplayListNew"
               %impeller::display-list-builder-create-display-list-new)
    %impeller::display-list
  (%impeller::builder %impeller::display-list-builder))

(cffi:defcstruct (%impeller::paint- :size 0))

(cffi:defctype %impeller::paint
               (claw-utils:claw-pointer (:struct %impeller::paint-)))

(declaim (inline %impeller::display-list-builder-draw-dashed-line))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawDashedLine"
               %impeller::display-list-builder-draw-dashed-line)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::from (claw-utils:claw-pointer %impeller::point))
  (%impeller::to (claw-utils:claw-pointer %impeller::point))
  (%impeller::on-length :float)
  (%impeller::off-length :float)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-display-list))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawDisplayList"
               %impeller::display-list-builder-draw-display-list)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::display-list %impeller::display-list)
  (%impeller::opacity :float))

(declaim (inline %impeller::display-list-builder-draw-line))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawLine"
               %impeller::display-list-builder-draw-line)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::from (claw-utils:claw-pointer %impeller::point))
  (%impeller::to (claw-utils:claw-pointer %impeller::point))
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-oval))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawOval"
               %impeller::display-list-builder-draw-oval)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::oval-bounds (claw-utils:claw-pointer %impeller::rect))
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-paint))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawPaint"
               %impeller::display-list-builder-draw-paint)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::paint %impeller::paint))

(cffi:defcstruct (%impeller::paragraph- :size 0))

(cffi:defctype %impeller::paragraph
               (claw-utils:claw-pointer (:struct %impeller::paragraph-)))

(declaim (inline %impeller::display-list-builder-draw-paragraph))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawParagraph"
               %impeller::display-list-builder-draw-paragraph)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::paragraph %impeller::paragraph)
  (%impeller::point (claw-utils:claw-pointer %impeller::point)))

(declaim (inline %impeller::display-list-builder-draw-path))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawPath"
               %impeller::display-list-builder-draw-path)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::path %impeller::path)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-rect))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawRect"
               %impeller::display-list-builder-draw-rect)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-rounded-rect))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawRoundedRect"
               %impeller::display-list-builder-draw-rounded-rect)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::radii (claw-utils:claw-pointer %impeller::rounding-radii))
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-rounded-rect-difference))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawRoundedRectDifference"
               %impeller::display-list-builder-draw-rounded-rect-difference)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::outer-rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::outer-radii (claw-utils:claw-pointer %impeller::rounding-radii))
  (%impeller::inner-rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::inner-radii (claw-utils:claw-pointer %impeller::rounding-radii))
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-shadow))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawShadow"
               %impeller::display-list-builder-draw-shadow)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::path %impeller::path)
  (%impeller::color (claw-utils:claw-pointer %impeller::color))
  (%impeller::elevation :float)
  (%impeller::occluder-is-transparent :bool)
  (%impeller::device-pixel-ratio :float))

(declaim (inline %impeller::display-list-builder-draw-texture))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawTexture"
               %impeller::display-list-builder-draw-texture)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::texture %impeller::texture)
  (%impeller::point (claw-utils:claw-pointer %impeller::point))
  (%impeller::sampling %impeller::texture-sampling)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-draw-texture-rect))

(cffi:defcfun ("ImpellerDisplayListBuilderDrawTextureRect"
               %impeller::display-list-builder-draw-texture-rect)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::texture %impeller::texture)
  (%impeller::src-rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::dst-rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::sampling %impeller::texture-sampling)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::display-list-builder-get-save-count))

(cffi:defcfun ("ImpellerDisplayListBuilderGetSaveCount"
               %impeller::display-list-builder-get-save-count)
    %impeller::uint32-t
  (%impeller::builder %impeller::display-list-builder))

(declaim (inline %impeller::display-list-builder-get-transform))

(cffi:defcfun ("ImpellerDisplayListBuilderGetTransform"
               %impeller::display-list-builder-get-transform)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::out-transform (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::display-list-builder-new))

(cffi:defcfun ("ImpellerDisplayListBuilderNew"
               %impeller::display-list-builder-new)
    %impeller::display-list-builder
  (%impeller::cull-rect (claw-utils:claw-pointer %impeller::rect)))

(declaim (inline %impeller::display-list-builder-release))

(cffi:defcfun ("ImpellerDisplayListBuilderRelease"
               %impeller::display-list-builder-release)
    :void
  (%impeller::builder %impeller::display-list-builder))

(declaim (inline %impeller::display-list-builder-reset-transform))

(cffi:defcfun ("ImpellerDisplayListBuilderResetTransform"
               %impeller::display-list-builder-reset-transform)
    :void
  (%impeller::builder %impeller::display-list-builder))

(declaim (inline %impeller::display-list-builder-restore))

(cffi:defcfun ("ImpellerDisplayListBuilderRestore"
               %impeller::display-list-builder-restore)
    :void
  (%impeller::builder %impeller::display-list-builder))

(declaim (inline %impeller::display-list-builder-restore-to-count))

(cffi:defcfun ("ImpellerDisplayListBuilderRestoreToCount"
               %impeller::display-list-builder-restore-to-count)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::count %impeller::uint32-t))

(declaim (inline %impeller::display-list-builder-retain))

(cffi:defcfun ("ImpellerDisplayListBuilderRetain"
               %impeller::display-list-builder-retain)
    :void
  (%impeller::builder %impeller::display-list-builder))

(declaim (inline %impeller::display-list-builder-rotate))

(cffi:defcfun ("ImpellerDisplayListBuilderRotate"
               %impeller::display-list-builder-rotate)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::angle-degrees :float))

(declaim (inline %impeller::display-list-builder-save))

(cffi:defcfun ("ImpellerDisplayListBuilderSave"
               %impeller::display-list-builder-save)
    :void
  (%impeller::builder %impeller::display-list-builder))

(cffi:defcstruct (%impeller::image-filter- :size 0))

(cffi:defctype %impeller::image-filter
               (claw-utils:claw-pointer (:struct %impeller::image-filter-)))

(declaim (inline %impeller::display-list-builder-save-layer))

(cffi:defcfun ("ImpellerDisplayListBuilderSaveLayer"
               %impeller::display-list-builder-save-layer)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::bounds (claw-utils:claw-pointer %impeller::rect))
  (%impeller::paint %impeller::paint)
  (%impeller::backdrop %impeller::image-filter))

(declaim (inline %impeller::display-list-builder-scale))

(cffi:defcfun ("ImpellerDisplayListBuilderScale"
               %impeller::display-list-builder-scale)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::x-scale :float)
  (%impeller::y-scale :float))

(declaim (inline %impeller::display-list-builder-set-transform))

(cffi:defcfun ("ImpellerDisplayListBuilderSetTransform"
               %impeller::display-list-builder-set-transform)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::transform (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::display-list-builder-transform))

(cffi:defcfun ("ImpellerDisplayListBuilderTransform"
               %impeller::display-list-builder-transform)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::transform (claw-utils:claw-pointer %impeller::matrix)))

(declaim (inline %impeller::display-list-builder-translate))

(cffi:defcfun ("ImpellerDisplayListBuilderTranslate"
               %impeller::display-list-builder-translate)
    :void
  (%impeller::builder %impeller::display-list-builder)
  (%impeller::x-translation :float)
  (%impeller::y-translation :float))

(declaim (inline %impeller::display-list-release))

(cffi:defcfun ("ImpellerDisplayListRelease" %impeller::display-list-release)
    :void
  (%impeller::display-list %impeller::display-list))

(declaim (inline %impeller::display-list-retain))

(cffi:defcfun ("ImpellerDisplayListRetain" %impeller::display-list-retain)
    :void
  (%impeller::display-list %impeller::display-list))

(cffi:defcstruct (%impeller::mapping :size 24))

(cffi:defctype %impeller::mapping (:struct %impeller::mapping))

(declaim (inline %impeller::fragment-program-new))

(cffi:defcfun ("ImpellerFragmentProgramNew" %impeller::fragment-program-new)
    %impeller::fragment-program
  (%impeller::data (claw-utils:claw-pointer %impeller::mapping))
  (%impeller::data-release-user-data (claw-utils:claw-pointer :void)))

(declaim (inline %impeller::fragment-program-release))

(cffi:defcfun ("ImpellerFragmentProgramRelease"
               %impeller::fragment-program-release)
    :void
  (%impeller::fragment-program %impeller::fragment-program))

(declaim (inline %impeller::fragment-program-retain))

(cffi:defcfun ("ImpellerFragmentProgramRetain"
               %impeller::fragment-program-retain)
    :void
  (%impeller::fragment-program %impeller::fragment-program))

(declaim (inline %impeller::get-version))

(cffi:defcfun ("ImpellerGetVersion" %impeller::get-version)
    %impeller::uint32-t
  &rest)

(cffi:defcstruct (%impeller::glyph-info- :size 0))

(cffi:defctype %impeller::glyph-info
               (claw-utils:claw-pointer (:struct %impeller::glyph-info-)))

(declaim (inline %impeller::glyph-info-get-grapheme-cluster-bounds))

(cffi:defcfun ("ImpellerGlyphInfoGetGraphemeClusterBounds"
               %impeller::glyph-info-get-grapheme-cluster-bounds)
    :void
  (%impeller::glyph-info %impeller::glyph-info)
  (%impeller::out-bounds (claw-utils:claw-pointer %impeller::rect)))

(declaim
 (inline %impeller::glyph-info-get-grapheme-cluster-code-unit-range-begin))

(cffi:defcfun ("ImpellerGlyphInfoGetGraphemeClusterCodeUnitRangeBegin"
               %impeller::glyph-info-get-grapheme-cluster-code-unit-range-begin)
    %impeller::size-t
  (%impeller::glyph-info %impeller::glyph-info))

(declaim
 (inline %impeller::glyph-info-get-grapheme-cluster-code-unit-range-end))

(cffi:defcfun ("ImpellerGlyphInfoGetGraphemeClusterCodeUnitRangeEnd"
               %impeller::glyph-info-get-grapheme-cluster-code-unit-range-end)
    %impeller::size-t
  (%impeller::glyph-info %impeller::glyph-info))

(cffi:defctype %impeller::text-direction %impeller::text-direction)

(declaim (inline %impeller::glyph-info-get-text-direction))

(cffi:defcfun ("ImpellerGlyphInfoGetTextDirection"
               %impeller::glyph-info-get-text-direction)
    %impeller::text-direction
  (%impeller::glyph-info %impeller::glyph-info))

(declaim (inline %impeller::glyph-info-is-ellipsis))

(cffi:defcfun ("ImpellerGlyphInfoIsEllipsis" %impeller::glyph-info-is-ellipsis)
    :bool
  (%impeller::glyph-info %impeller::glyph-info))

(declaim (inline %impeller::glyph-info-release))

(cffi:defcfun ("ImpellerGlyphInfoRelease" %impeller::glyph-info-release)
    :void
  (%impeller::glyph-info %impeller::glyph-info))

(declaim (inline %impeller::glyph-info-retain))

(cffi:defcfun ("ImpellerGlyphInfoRetain" %impeller::glyph-info-retain)
    :void
  (%impeller::glyph-info %impeller::glyph-info))

(declaim (inline %impeller::image-filter-create-blur-new))

(cffi:defcfun ("ImpellerImageFilterCreateBlurNew"
               %impeller::image-filter-create-blur-new)
    %impeller::image-filter
  (%impeller::x-sigma :float)
  (%impeller::y-sigma :float)
  (%impeller::tile-mode %impeller::tile-mode))

(declaim (inline %impeller::image-filter-create-compose-new))

(cffi:defcfun ("ImpellerImageFilterCreateComposeNew"
               %impeller::image-filter-create-compose-new)
    %impeller::image-filter
  (%impeller::outer %impeller::image-filter)
  (%impeller::inner %impeller::image-filter))

(declaim (inline %impeller::image-filter-create-dilate-new))

(cffi:defcfun ("ImpellerImageFilterCreateDilateNew"
               %impeller::image-filter-create-dilate-new)
    %impeller::image-filter
  (%impeller::x-radius :float)
  (%impeller::y-radius :float))

(declaim (inline %impeller::image-filter-create-erode-new))

(cffi:defcfun ("ImpellerImageFilterCreateErodeNew"
               %impeller::image-filter-create-erode-new)
    %impeller::image-filter
  (%impeller::x-radius :float)
  (%impeller::y-radius :float))

(declaim (inline %impeller::image-filter-create-fragment-program-new))

(cffi:defcfun ("ImpellerImageFilterCreateFragmentProgramNew"
               %impeller::image-filter-create-fragment-program-new)
    %impeller::image-filter
  (%impeller::context %impeller::context)
  (%impeller::fragment-program %impeller::fragment-program)
  (%impeller::samplers (claw-utils:claw-pointer %impeller::texture))
  (%impeller::samplers-count %impeller::size-t)
  (%impeller::data (claw-utils:claw-pointer %impeller::uint8-t))
  (%impeller::data-bytes-length %impeller::size-t))

(declaim (inline %impeller::image-filter-create-matrix-new))

(cffi:defcfun ("ImpellerImageFilterCreateMatrixNew"
               %impeller::image-filter-create-matrix-new)
    %impeller::image-filter
  (%impeller::matrix (claw-utils:claw-pointer %impeller::matrix))
  (%impeller::sampling %impeller::texture-sampling))

(declaim (inline %impeller::image-filter-release))

(cffi:defcfun ("ImpellerImageFilterRelease" %impeller::image-filter-release)
    :void
  (%impeller::image-filter %impeller::image-filter))

(declaim (inline %impeller::image-filter-retain))

(cffi:defcfun ("ImpellerImageFilterRetain" %impeller::image-filter-retain)
    :void
  (%impeller::image-filter %impeller::image-filter))

(cffi:defcstruct (%impeller::line-metrics- :size 0))

(cffi:defctype %impeller::line-metrics
               (claw-utils:claw-pointer (:struct %impeller::line-metrics-)))

(declaim (inline %impeller::line-metrics-get-ascent))

(cffi:defcfun ("ImpellerLineMetricsGetAscent"
               %impeller::line-metrics-get-ascent)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-baseline))

(cffi:defcfun ("ImpellerLineMetricsGetBaseline"
               %impeller::line-metrics-get-baseline)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-code-unit-end-index))

(cffi:defcfun ("ImpellerLineMetricsGetCodeUnitEndIndex"
               %impeller::line-metrics-get-code-unit-end-index)
    %impeller::size-t
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim
 (inline %impeller::line-metrics-get-code-unit-end-index-excluding-whitespace))

(cffi:defcfun ("ImpellerLineMetricsGetCodeUnitEndIndexExcludingWhitespace"
               %impeller::line-metrics-get-code-unit-end-index-excluding-whitespace)
    %impeller::size-t
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim
 (inline %impeller::line-metrics-get-code-unit-end-index-including-newline))

(cffi:defcfun ("ImpellerLineMetricsGetCodeUnitEndIndexIncludingNewline"
               %impeller::line-metrics-get-code-unit-end-index-including-newline)
    %impeller::size-t
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-code-unit-start-index))

(cffi:defcfun ("ImpellerLineMetricsGetCodeUnitStartIndex"
               %impeller::line-metrics-get-code-unit-start-index)
    %impeller::size-t
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-descent))

(cffi:defcfun ("ImpellerLineMetricsGetDescent"
               %impeller::line-metrics-get-descent)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-height))

(cffi:defcfun ("ImpellerLineMetricsGetHeight"
               %impeller::line-metrics-get-height)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-left))

(cffi:defcfun ("ImpellerLineMetricsGetLeft" %impeller::line-metrics-get-left)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-unscaled-ascent))

(cffi:defcfun ("ImpellerLineMetricsGetUnscaledAscent"
               %impeller::line-metrics-get-unscaled-ascent)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-get-width))

(cffi:defcfun ("ImpellerLineMetricsGetWidth" %impeller::line-metrics-get-width)
    :double
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-is-hardbreak))

(cffi:defcfun ("ImpellerLineMetricsIsHardbreak"
               %impeller::line-metrics-is-hardbreak)
    :bool
  (%impeller::metrics %impeller::line-metrics)
  (%impeller::line %impeller::size-t))

(declaim (inline %impeller::line-metrics-release))

(cffi:defcfun ("ImpellerLineMetricsRelease" %impeller::line-metrics-release)
    :void
  (%impeller::line-metrics %impeller::line-metrics))

(declaim (inline %impeller::line-metrics-retain))

(cffi:defcfun ("ImpellerLineMetricsRetain" %impeller::line-metrics-retain)
    :void
  (%impeller::line-metrics %impeller::line-metrics))

(cffi:defcstruct (%impeller::mask-filter- :size 0))

(cffi:defctype %impeller::mask-filter
               (claw-utils:claw-pointer (:struct %impeller::mask-filter-)))

(cffi:defctype %impeller::blur-style %impeller::blur-style)

(declaim (inline %impeller::mask-filter-create-blur-new))

(cffi:defcfun ("ImpellerMaskFilterCreateBlurNew"
               %impeller::mask-filter-create-blur-new)
    %impeller::mask-filter
  (%impeller::style %impeller::blur-style)
  (%impeller::sigma :float))

(declaim (inline %impeller::mask-filter-release))

(cffi:defcfun ("ImpellerMaskFilterRelease" %impeller::mask-filter-release)
    :void
  (%impeller::mask-filter %impeller::mask-filter))

(declaim (inline %impeller::mask-filter-retain))

(cffi:defcfun ("ImpellerMaskFilterRetain" %impeller::mask-filter-retain)
    :void
  (%impeller::mask-filter %impeller::mask-filter))

(declaim (inline %impeller::paint-new))

(cffi:defcfun ("ImpellerPaintNew" %impeller::paint-new)
    %impeller::paint
  &rest)

(declaim (inline %impeller::paint-release))

(cffi:defcfun ("ImpellerPaintRelease" %impeller::paint-release)
    :void
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::paint-retain))

(cffi:defcfun ("ImpellerPaintRetain" %impeller::paint-retain)
    :void
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::paint-set-blend-mode))

(cffi:defcfun ("ImpellerPaintSetBlendMode" %impeller::paint-set-blend-mode)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::mode %impeller::blend-mode))

(declaim (inline %impeller::paint-set-color))

(cffi:defcfun ("ImpellerPaintSetColor" %impeller::paint-set-color)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::color (claw-utils:claw-pointer %impeller::color)))

(declaim (inline %impeller::paint-set-color-filter))

(cffi:defcfun ("ImpellerPaintSetColorFilter" %impeller::paint-set-color-filter)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::color-filter %impeller::color-filter))

(declaim (inline %impeller::paint-set-color-source))

(cffi:defcfun ("ImpellerPaintSetColorSource" %impeller::paint-set-color-source)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::color-source %impeller::color-source))

(cffi:defctype %impeller::draw-style %impeller::draw-style)

(declaim (inline %impeller::paint-set-draw-style))

(cffi:defcfun ("ImpellerPaintSetDrawStyle" %impeller::paint-set-draw-style)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::style %impeller::draw-style))

(declaim (inline %impeller::paint-set-image-filter))

(cffi:defcfun ("ImpellerPaintSetImageFilter" %impeller::paint-set-image-filter)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::image-filter %impeller::image-filter))

(declaim (inline %impeller::paint-set-mask-filter))

(cffi:defcfun ("ImpellerPaintSetMaskFilter" %impeller::paint-set-mask-filter)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::mask-filter %impeller::mask-filter))

(cffi:defctype %impeller::stroke-cap %impeller::stroke-cap)

(declaim (inline %impeller::paint-set-stroke-cap))

(cffi:defcfun ("ImpellerPaintSetStrokeCap" %impeller::paint-set-stroke-cap)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::cap %impeller::stroke-cap))

(cffi:defctype %impeller::stroke-join %impeller::stroke-join)

(declaim (inline %impeller::paint-set-stroke-join))

(cffi:defcfun ("ImpellerPaintSetStrokeJoin" %impeller::paint-set-stroke-join)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::join %impeller::stroke-join))

(declaim (inline %impeller::paint-set-stroke-miter))

(cffi:defcfun ("ImpellerPaintSetStrokeMiter" %impeller::paint-set-stroke-miter)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::miter :float))

(declaim (inline %impeller::paint-set-stroke-width))

(cffi:defcfun ("ImpellerPaintSetStrokeWidth" %impeller::paint-set-stroke-width)
    :void
  (%impeller::paint %impeller::paint)
  (%impeller::width :float))

(cffi:defcstruct (%impeller::paragraph-builder- :size 0))

(cffi:defctype %impeller::paragraph-builder
               (claw-utils:claw-pointer
                (:struct %impeller::paragraph-builder-)))

(declaim (inline %impeller::paragraph-builder-add-text))

(cffi:defcfun ("ImpellerParagraphBuilderAddText"
               %impeller::paragraph-builder-add-text)
    :void
  (%impeller::paragraph-builder %impeller::paragraph-builder)
  (%impeller::data (claw-utils:claw-pointer %impeller::uint8-t))
  (%impeller::length %impeller::uint32-t))

(declaim (inline %impeller::paragraph-builder-build-paragraph-new))

(cffi:defcfun ("ImpellerParagraphBuilderBuildParagraphNew"
               %impeller::paragraph-builder-build-paragraph-new)
    %impeller::paragraph
  (%impeller::paragraph-builder %impeller::paragraph-builder)
  (%impeller::width :float))

(cffi:defcstruct (%impeller::typography-context- :size 0))

(cffi:defctype %impeller::typography-context
               (claw-utils:claw-pointer
                (:struct %impeller::typography-context-)))

(declaim (inline %impeller::paragraph-builder-new))

(cffi:defcfun ("ImpellerParagraphBuilderNew" %impeller::paragraph-builder-new)
    %impeller::paragraph-builder
  (%impeller::context %impeller::typography-context))

(declaim (inline %impeller::paragraph-builder-pop-style))

(cffi:defcfun ("ImpellerParagraphBuilderPopStyle"
               %impeller::paragraph-builder-pop-style)
    :void
  (%impeller::paragraph-builder %impeller::paragraph-builder))

(cffi:defcstruct (%impeller::paragraph-style- :size 0))

(cffi:defctype %impeller::paragraph-style
               (claw-utils:claw-pointer (:struct %impeller::paragraph-style-)))

(declaim (inline %impeller::paragraph-builder-push-style))

(cffi:defcfun ("ImpellerParagraphBuilderPushStyle"
               %impeller::paragraph-builder-push-style)
    :void
  (%impeller::paragraph-builder %impeller::paragraph-builder)
  (%impeller::style %impeller::paragraph-style))

(declaim (inline %impeller::paragraph-builder-release))

(cffi:defcfun ("ImpellerParagraphBuilderRelease"
               %impeller::paragraph-builder-release)
    :void
  (%impeller::paragraph-builder %impeller::paragraph-builder))

(declaim (inline %impeller::paragraph-builder-retain))

(cffi:defcfun ("ImpellerParagraphBuilderRetain"
               %impeller::paragraph-builder-retain)
    :void
  (%impeller::paragraph-builder %impeller::paragraph-builder))

(declaim (inline %impeller::paragraph-create-glyph-info-at-code-unit-index-new))

(cffi:defcfun ("ImpellerParagraphCreateGlyphInfoAtCodeUnitIndexNew"
               %impeller::paragraph-create-glyph-info-at-code-unit-index-new)
    %impeller::glyph-info
  (%impeller::paragraph %impeller::paragraph)
  (%impeller::code-unit-index %impeller::size-t))

(declaim
 (inline %impeller::paragraph-create-glyph-info-at-paragraph-coordinates-new))

(cffi:defcfun ("ImpellerParagraphCreateGlyphInfoAtParagraphCoordinatesNew"
               %impeller::paragraph-create-glyph-info-at-paragraph-coordinates-new)
    %impeller::glyph-info
  (%impeller::paragraph %impeller::paragraph)
  (%impeller::x :double)
  (%impeller::y :double))

(declaim (inline %impeller::paragraph-get-alphabetic-baseline))

(cffi:defcfun ("ImpellerParagraphGetAlphabeticBaseline"
               %impeller::paragraph-get-alphabetic-baseline)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-height))

(cffi:defcfun ("ImpellerParagraphGetHeight" %impeller::paragraph-get-height)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-ideographic-baseline))

(cffi:defcfun ("ImpellerParagraphGetIdeographicBaseline"
               %impeller::paragraph-get-ideographic-baseline)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-line-count))

(cffi:defcfun ("ImpellerParagraphGetLineCount"
               %impeller::paragraph-get-line-count)
    %impeller::uint32-t
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-line-metrics))

(cffi:defcfun ("ImpellerParagraphGetLineMetrics"
               %impeller::paragraph-get-line-metrics)
    %impeller::line-metrics
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-longest-line-width))

(cffi:defcfun ("ImpellerParagraphGetLongestLineWidth"
               %impeller::paragraph-get-longest-line-width)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-max-intrinsic-width))

(cffi:defcfun ("ImpellerParagraphGetMaxIntrinsicWidth"
               %impeller::paragraph-get-max-intrinsic-width)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-max-width))

(cffi:defcfun ("ImpellerParagraphGetMaxWidth"
               %impeller::paragraph-get-max-width)
    :float
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-get-min-intrinsic-width))

(cffi:defcfun ("ImpellerParagraphGetMinIntrinsicWidth"
               %impeller::paragraph-get-min-intrinsic-width)
    :float
  (%impeller::paragraph %impeller::paragraph))

(cffi:defcstruct (%impeller::range :size 8))

(cffi:defctype %impeller::range (:struct %impeller::range))

(declaim (inline %impeller::paragraph-get-word-boundary))

(cffi:defcfun ("ImpellerParagraphGetWordBoundary"
               %impeller::paragraph-get-word-boundary)
    :void
  (%impeller::paragraph %impeller::paragraph)
  (%impeller::code-unit-index %impeller::size-t)
  (%impeller::out-range (claw-utils:claw-pointer %impeller::range)))

(declaim (inline %impeller::paragraph-release))

(cffi:defcfun ("ImpellerParagraphRelease" %impeller::paragraph-release)
    :void
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-retain))

(cffi:defcfun ("ImpellerParagraphRetain" %impeller::paragraph-retain)
    :void
  (%impeller::paragraph %impeller::paragraph))

(declaim (inline %impeller::paragraph-style-new))

(cffi:defcfun ("ImpellerParagraphStyleNew" %impeller::paragraph-style-new)
    %impeller::paragraph-style
  &rest)

(declaim (inline %impeller::paragraph-style-release))

(cffi:defcfun ("ImpellerParagraphStyleRelease"
               %impeller::paragraph-style-release)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style))

(declaim (inline %impeller::paragraph-style-retain))

(cffi:defcfun ("ImpellerParagraphStyleRetain" %impeller::paragraph-style-retain)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style))

(declaim (inline %impeller::paragraph-style-set-background))

(cffi:defcfun ("ImpellerParagraphStyleSetBackground"
               %impeller::paragraph-style-set-background)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::paragraph-style-set-ellipsis))

(cffi:defcfun ("ImpellerParagraphStyleSetEllipsis"
               %impeller::paragraph-style-set-ellipsis)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::ellipsis claw-utils:claw-string))

(declaim (inline %impeller::paragraph-style-set-font-family))

(cffi:defcfun ("ImpellerParagraphStyleSetFontFamily"
               %impeller::paragraph-style-set-font-family)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::family-name claw-utils:claw-string))

(declaim (inline %impeller::paragraph-style-set-font-size))

(cffi:defcfun ("ImpellerParagraphStyleSetFontSize"
               %impeller::paragraph-style-set-font-size)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::size :float))

(cffi:defctype %impeller::font-style %impeller::font-style)

(declaim (inline %impeller::paragraph-style-set-font-style))

(cffi:defcfun ("ImpellerParagraphStyleSetFontStyle"
               %impeller::paragraph-style-set-font-style)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::style %impeller::font-style))

(cffi:defctype %impeller::font-weight %impeller::font-weight)

(declaim (inline %impeller::paragraph-style-set-font-weight))

(cffi:defcfun ("ImpellerParagraphStyleSetFontWeight"
               %impeller::paragraph-style-set-font-weight)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::weight %impeller::font-weight))

(declaim (inline %impeller::paragraph-style-set-foreground))

(cffi:defcfun ("ImpellerParagraphStyleSetForeground"
               %impeller::paragraph-style-set-foreground)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::paint %impeller::paint))

(declaim (inline %impeller::paragraph-style-set-height))

(cffi:defcfun ("ImpellerParagraphStyleSetHeight"
               %impeller::paragraph-style-set-height)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::height :float))

(declaim (inline %impeller::paragraph-style-set-locale))

(cffi:defcfun ("ImpellerParagraphStyleSetLocale"
               %impeller::paragraph-style-set-locale)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::locale claw-utils:claw-string))

(declaim (inline %impeller::paragraph-style-set-max-lines))

(cffi:defcfun ("ImpellerParagraphStyleSetMaxLines"
               %impeller::paragraph-style-set-max-lines)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::max-lines %impeller::uint32-t))

(cffi:defctype %impeller::text-alignment %impeller::text-alignment)

(declaim (inline %impeller::paragraph-style-set-text-alignment))

(cffi:defcfun ("ImpellerParagraphStyleSetTextAlignment"
               %impeller::paragraph-style-set-text-alignment)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::align %impeller::text-alignment))

(cffi:defcstruct (%impeller::text-decoration :size 32))

(cffi:defctype %impeller::text-decoration (:struct %impeller::text-decoration))

(declaim (inline %impeller::paragraph-style-set-text-decoration))

(cffi:defcfun ("ImpellerParagraphStyleSetTextDecoration"
               %impeller::paragraph-style-set-text-decoration)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::decoration (claw-utils:claw-pointer %impeller::text-decoration)))

(declaim (inline %impeller::paragraph-style-set-text-direction))

(cffi:defcfun ("ImpellerParagraphStyleSetTextDirection"
               %impeller::paragraph-style-set-text-direction)
    :void
  (%impeller::paragraph-style %impeller::paragraph-style)
  (%impeller::direction %impeller::text-direction))

(cffi:defcstruct (%impeller::path-builder- :size 0))

(cffi:defctype %impeller::path-builder
               (claw-utils:claw-pointer (:struct %impeller::path-builder-)))

(declaim (inline %impeller::path-builder-add-arc))

(cffi:defcfun ("ImpellerPathBuilderAddArc" %impeller::path-builder-add-arc)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::oval-bounds (claw-utils:claw-pointer %impeller::rect))
  (%impeller::start-angle-degrees :float)
  (%impeller::end-angle-degrees :float))

(declaim (inline %impeller::path-builder-add-oval))

(cffi:defcfun ("ImpellerPathBuilderAddOval" %impeller::path-builder-add-oval)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::oval-bounds (claw-utils:claw-pointer %impeller::rect)))

(declaim (inline %impeller::path-builder-add-rect))

(cffi:defcfun ("ImpellerPathBuilderAddRect" %impeller::path-builder-add-rect)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect)))

(declaim (inline %impeller::path-builder-add-rounded-rect))

(cffi:defcfun ("ImpellerPathBuilderAddRoundedRect"
               %impeller::path-builder-add-rounded-rect)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::rect (claw-utils:claw-pointer %impeller::rect))
  (%impeller::rounding-radii
   (claw-utils:claw-pointer %impeller::rounding-radii)))

(declaim (inline %impeller::path-builder-close))

(cffi:defcfun ("ImpellerPathBuilderClose" %impeller::path-builder-close)
    :void
  (%impeller::builder %impeller::path-builder))

(cffi:defctype %impeller::fill-type %impeller::fill-type)

(declaim (inline %impeller::path-builder-copy-path-new))

(cffi:defcfun ("ImpellerPathBuilderCopyPathNew"
               %impeller::path-builder-copy-path-new)
    %impeller::path
  (%impeller::builder %impeller::path-builder)
  (%impeller::fill %impeller::fill-type))

(declaim (inline %impeller::path-builder-cubic-curve-to))

(cffi:defcfun ("ImpellerPathBuilderCubicCurveTo"
               %impeller::path-builder-cubic-curve-to)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::control-point-1 (claw-utils:claw-pointer %impeller::point))
  (%impeller::control-point-2 (claw-utils:claw-pointer %impeller::point))
  (%impeller::end-point (claw-utils:claw-pointer %impeller::point)))

(declaim (inline %impeller::path-builder-line-to))

(cffi:defcfun ("ImpellerPathBuilderLineTo" %impeller::path-builder-line-to)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::location (claw-utils:claw-pointer %impeller::point)))

(declaim (inline %impeller::path-builder-move-to))

(cffi:defcfun ("ImpellerPathBuilderMoveTo" %impeller::path-builder-move-to)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::location (claw-utils:claw-pointer %impeller::point)))

(declaim (inline %impeller::path-builder-new))

(cffi:defcfun ("ImpellerPathBuilderNew" %impeller::path-builder-new)
    %impeller::path-builder
  &rest)

(declaim (inline %impeller::path-builder-quadratic-curve-to))

(cffi:defcfun ("ImpellerPathBuilderQuadraticCurveTo"
               %impeller::path-builder-quadratic-curve-to)
    :void
  (%impeller::builder %impeller::path-builder)
  (%impeller::control-point (claw-utils:claw-pointer %impeller::point))
  (%impeller::end-point (claw-utils:claw-pointer %impeller::point)))

(declaim (inline %impeller::path-builder-release))

(cffi:defcfun ("ImpellerPathBuilderRelease" %impeller::path-builder-release)
    :void
  (%impeller::builder %impeller::path-builder))

(declaim (inline %impeller::path-builder-retain))

(cffi:defcfun ("ImpellerPathBuilderRetain" %impeller::path-builder-retain)
    :void
  (%impeller::builder %impeller::path-builder))

(declaim (inline %impeller::path-builder-take-path-new))

(cffi:defcfun ("ImpellerPathBuilderTakePathNew"
               %impeller::path-builder-take-path-new)
    %impeller::path
  (%impeller::builder %impeller::path-builder)
  (%impeller::fill %impeller::fill-type))

(declaim (inline %impeller::path-get-bounds))

(cffi:defcfun ("ImpellerPathGetBounds" %impeller::path-get-bounds)
    :void
  (%impeller::path %impeller::path)
  (%impeller::out-bounds (claw-utils:claw-pointer %impeller::rect)))

(declaim (inline %impeller::path-release))

(cffi:defcfun ("ImpellerPathRelease" %impeller::path-release)
    :void
  (%impeller::path %impeller::path))

(declaim (inline %impeller::path-retain))

(cffi:defcfun ("ImpellerPathRetain" %impeller::path-retain)
    :void
  (%impeller::path %impeller::path))

(cffi:defcstruct (%impeller::surface- :size 0))

(cffi:defctype %impeller::surface
               (claw-utils:claw-pointer (:struct %impeller::surface-)))

(cffi:defctype %impeller::uint64-t :unsigned-long)

(cffi:defctype %impeller::pixel-format %impeller::pixel-format)

(cffi:defcstruct (%impeller::i-size :size 8))

(cffi:defctype %impeller::i-size (:struct %impeller::i-size))

(declaim (inline %impeller::surface-create-wrapped-fbo-new))

(cffi:defcfun ("ImpellerSurfaceCreateWrappedFBONew"
               %impeller::surface-create-wrapped-fbo-new)
    %impeller::surface
  (%impeller::context %impeller::context)
  (%impeller::fbo %impeller::uint64-t)
  (%impeller::format %impeller::pixel-format)
  (%impeller::size (claw-utils:claw-pointer %impeller::i-size)))

(declaim (inline %impeller::surface-create-wrapped-metal-drawable-new))

(cffi:defcfun ("ImpellerSurfaceCreateWrappedMetalDrawableNew"
               %impeller::surface-create-wrapped-metal-drawable-new)
    %impeller::surface
  (%impeller::context %impeller::context)
  (%impeller::metal-drawable (claw-utils:claw-pointer :void)))

(declaim (inline %impeller::surface-draw-display-list))

(cffi:defcfun ("ImpellerSurfaceDrawDisplayList"
               %impeller::surface-draw-display-list)
    :bool
  (%impeller::surface %impeller::surface)
  (%impeller::display-list %impeller::display-list))

(declaim (inline %impeller::surface-present))

(cffi:defcfun ("ImpellerSurfacePresent" %impeller::surface-present)
    :bool
  (%impeller::surface %impeller::surface))

(declaim (inline %impeller::surface-release))

(cffi:defcfun ("ImpellerSurfaceRelease" %impeller::surface-release)
    :void
  (%impeller::surface %impeller::surface))

(declaim (inline %impeller::surface-retain))

(cffi:defcfun ("ImpellerSurfaceRetain" %impeller::surface-retain)
    :void
  (%impeller::surface %impeller::surface))

(cffi:defcstruct (%impeller::texture-descriptor :size 16))

(cffi:defctype %impeller::texture-descriptor
               (:struct %impeller::texture-descriptor))

(declaim (inline %impeller::texture-create-with-contents-new))

(cffi:defcfun ("ImpellerTextureCreateWithContentsNew"
               %impeller::texture-create-with-contents-new)
    %impeller::texture
  (%impeller::context %impeller::context)
  (%impeller::descriptor
   (claw-utils:claw-pointer %impeller::texture-descriptor))
  (%impeller::contents (claw-utils:claw-pointer %impeller::mapping))
  (%impeller::contents-on-release-user-data (claw-utils:claw-pointer :void)))

(declaim (inline %impeller::texture-create-with-open-gl-texture-handle-new))

(cffi:defcfun ("ImpellerTextureCreateWithOpenGLTextureHandleNew"
               %impeller::texture-create-with-open-gl-texture-handle-new)
    %impeller::texture
  (%impeller::context %impeller::context)
  (%impeller::descriptor
   (claw-utils:claw-pointer %impeller::texture-descriptor))
  (%impeller::handle %impeller::uint64-t))

(declaim (inline %impeller::texture-get-open-gl-handle))

(cffi:defcfun ("ImpellerTextureGetOpenGLHandle"
               %impeller::texture-get-open-gl-handle)
    %impeller::uint64-t
  (%impeller::texture %impeller::texture))

(declaim (inline %impeller::texture-release))

(cffi:defcfun ("ImpellerTextureRelease" %impeller::texture-release)
    :void
  (%impeller::texture %impeller::texture))

(declaim (inline %impeller::texture-retain))

(cffi:defcfun ("ImpellerTextureRetain" %impeller::texture-retain)
    :void
  (%impeller::texture %impeller::texture))

(declaim (inline %impeller::typography-context-new))

(cffi:defcfun ("ImpellerTypographyContextNew" %impeller::typography-context-new)
    %impeller::typography-context
  &rest)

(declaim (inline %impeller::typography-context-register-font))

(cffi:defcfun ("ImpellerTypographyContextRegisterFont"
               %impeller::typography-context-register-font)
    :bool
  (%impeller::context %impeller::typography-context)
  (%impeller::contents (claw-utils:claw-pointer %impeller::mapping))
  (%impeller::contents-on-release-user-data (claw-utils:claw-pointer :void))
  (%impeller::family-name-alias claw-utils:claw-string))

(declaim (inline %impeller::typography-context-release))

(cffi:defcfun ("ImpellerTypographyContextRelease"
               %impeller::typography-context-release)
    :void
  (%impeller::context %impeller::typography-context))

(declaim (inline %impeller::typography-context-retain))

(cffi:defcfun ("ImpellerTypographyContextRetain"
               %impeller::typography-context-retain)
    :void
  (%impeller::context %impeller::typography-context))

(cffi:defcstruct (%impeller::vulkan-swapchain- :size 0))

(cffi:defctype %impeller::vulkan-swapchain
               (claw-utils:claw-pointer (:struct %impeller::vulkan-swapchain-)))

(declaim (inline %impeller::vulkan-swapchain-acquire-next-surface-new))

(cffi:defcfun ("ImpellerVulkanSwapchainAcquireNextSurfaceNew"
               %impeller::vulkan-swapchain-acquire-next-surface-new)
    %impeller::surface
  (%impeller::swapchain %impeller::vulkan-swapchain))

(declaim (inline %impeller::vulkan-swapchain-create-new))

(cffi:defcfun ("ImpellerVulkanSwapchainCreateNew"
               %impeller::vulkan-swapchain-create-new)
    %impeller::vulkan-swapchain
  (%impeller::context %impeller::context)
  (%impeller::vulkan-surface-khr (claw-utils:claw-pointer :void)))

(declaim (inline %impeller::vulkan-swapchain-release))

(cffi:defcfun ("ImpellerVulkanSwapchainRelease"
               %impeller::vulkan-swapchain-release)
    :void
  (%impeller::swapchain %impeller::vulkan-swapchain))

(declaim (inline %impeller::vulkan-swapchain-retain))

(cffi:defcfun ("ImpellerVulkanSwapchainRetain"
               %impeller::vulkan-swapchain-retain)
    :void
  (%impeller::swapchain %impeller::vulkan-swapchain))

(cffi:defcstruct (%impeller::size :size 8))

(cffi:defctype %impeller::callback (claw-utils:claw-pointer :void))

(cffi:defctype %impeller::color-space %impeller::color-space)

(cffi:defctype %impeller::size (:struct %impeller::size))

(cffi:defctype %impeller::text-decoration-style
               %impeller::text-decoration-style)

(cffi:defctype %impeller::text-decoration-type %impeller::text-decoration-type)

(cffi:defctype %impeller::vulkan-proc-address-callback
               (claw-utils:claw-pointer :void))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%impeller::+export+ :%impeller)
  (export '%impeller::+export-decoration+ :%impeller)
  (export '%impeller::+extern-c+ :%impeller)
  (export '%impeller::+extern-c-begin+ :%impeller)
  (export '%impeller::+nodiscard+ :%impeller)
  (export '%impeller::+nonnull+ :%impeller)
  (export '%impeller::+nullable+ :%impeller)
  (export '%impeller::+version+ :%impeller)
  (export '%impeller::+version-major+ :%impeller)
  (export '%impeller::+version-minor+ :%impeller)
  (export '%impeller::+version-patch+ :%impeller)
  (export '%impeller::+version-variant+ :%impeller)
  (export '%impeller::blend-mode :%impeller)
  (export '%impeller::blur-style :%impeller)
  (export '%impeller::clip-operation :%impeller)
  (export '%impeller::color-space :%impeller)
  (export '%impeller::draw-style :%impeller)
  (export '%impeller::fill-type :%impeller)
  (export '%impeller::font-style :%impeller)
  (export '%impeller::font-weight :%impeller)
  (export '%impeller::pixel-format :%impeller)
  (export '%impeller::stroke-cap :%impeller)
  (export '%impeller::stroke-join :%impeller)
  (export '%impeller::text-alignment :%impeller)
  (export '%impeller::text-decoration-style :%impeller)
  (export '%impeller::text-decoration-type :%impeller)
  (export '%impeller::text-direction :%impeller)
  (export '%impeller::texture-sampling :%impeller)
  (export '%impeller::tile-mode :%impeller)
  (export '%impeller::color-filter- :%impeller)
  (export '%impeller::color-filter :%impeller)
  (export '%impeller::color :%impeller)
  (export '%impeller::color-filter-create-blend-new :%impeller)
  (export '%impeller::color-matrix :%impeller)
  (export '%impeller::color-filter-create-color-matrix-new :%impeller)
  (export '%impeller::color-filter-release :%impeller)
  (export '%impeller::color-filter-retain :%impeller)
  (export '%impeller::color-source- :%impeller)
  (export '%impeller::color-source :%impeller)
  (export '%impeller::point :%impeller)
  (export '%impeller::uint32-t :%impeller)
  (export '%impeller::matrix :%impeller)
  (export '%impeller::color-source-create-conical-gradient-new :%impeller)
  (export '%impeller::context- :%impeller)
  (export '%impeller::context :%impeller)
  (export '%impeller::fragment-program- :%impeller)
  (export '%impeller::fragment-program :%impeller)
  (export '%impeller::texture- :%impeller)
  (export '%impeller::texture :%impeller)
  (export '%impeller::uint8-t :%impeller)
  (export '%impeller::size-t :%impeller)
  (export '%impeller::color-source-create-fragment-program-new :%impeller)
  (export '%impeller::color-source-create-image-new :%impeller)
  (export '%impeller::color-source-create-linear-gradient-new :%impeller)
  (export '%impeller::color-source-create-radial-gradient-new :%impeller)
  (export '%impeller::color-source-create-sweep-gradient-new :%impeller)
  (export '%impeller::color-source-release :%impeller)
  (export '%impeller::color-source-retain :%impeller)
  (export '%impeller::context-create-metal-new :%impeller)
  (export '%impeller::proc-address-callback :%impeller)
  (export '%impeller::context-create-open-gles-new :%impeller)
  (export '%impeller::context-vulkan-settings :%impeller)
  (export '%impeller::context-create-vulkan-new :%impeller)
  (export '%impeller::context-vulkan-info :%impeller)
  (export '%impeller::context-get-vulkan-info :%impeller)
  (export '%impeller::context-release :%impeller)
  (export '%impeller::context-retain :%impeller)
  (export '%impeller::display-list-builder- :%impeller)
  (export '%impeller::display-list-builder :%impeller)
  (export '%impeller::rect :%impeller)
  (export '%impeller::display-list-builder-clip-oval :%impeller)
  (export '%impeller::path- :%impeller)
  (export '%impeller::path :%impeller)
  (export '%impeller::display-list-builder-clip-path :%impeller)
  (export '%impeller::display-list-builder-clip-rect :%impeller)
  (export '%impeller::rounding-radii :%impeller)
  (export '%impeller::display-list-builder-clip-rounded-rect :%impeller)
  (export '%impeller::display-list- :%impeller)
  (export '%impeller::display-list :%impeller)
  (export '%impeller::display-list-builder-create-display-list-new :%impeller)
  (export '%impeller::paint- :%impeller)
  (export '%impeller::paint :%impeller)
  (export '%impeller::display-list-builder-draw-dashed-line :%impeller)
  (export '%impeller::display-list-builder-draw-display-list :%impeller)
  (export '%impeller::display-list-builder-draw-line :%impeller)
  (export '%impeller::display-list-builder-draw-oval :%impeller)
  (export '%impeller::display-list-builder-draw-paint :%impeller)
  (export '%impeller::paragraph- :%impeller)
  (export '%impeller::paragraph :%impeller)
  (export '%impeller::display-list-builder-draw-paragraph :%impeller)
  (export '%impeller::display-list-builder-draw-path :%impeller)
  (export '%impeller::display-list-builder-draw-rect :%impeller)
  (export '%impeller::display-list-builder-draw-rounded-rect :%impeller)
  (export '%impeller::display-list-builder-draw-rounded-rect-difference
          :%impeller)
  (export '%impeller::display-list-builder-draw-shadow :%impeller)
  (export '%impeller::display-list-builder-draw-texture :%impeller)
  (export '%impeller::display-list-builder-draw-texture-rect :%impeller)
  (export '%impeller::display-list-builder-get-save-count :%impeller)
  (export '%impeller::display-list-builder-get-transform :%impeller)
  (export '%impeller::display-list-builder-new :%impeller)
  (export '%impeller::display-list-builder-release :%impeller)
  (export '%impeller::display-list-builder-reset-transform :%impeller)
  (export '%impeller::display-list-builder-restore :%impeller)
  (export '%impeller::display-list-builder-restore-to-count :%impeller)
  (export '%impeller::display-list-builder-retain :%impeller)
  (export '%impeller::display-list-builder-rotate :%impeller)
  (export '%impeller::display-list-builder-save :%impeller)
  (export '%impeller::image-filter- :%impeller)
  (export '%impeller::image-filter :%impeller)
  (export '%impeller::display-list-builder-save-layer :%impeller)
  (export '%impeller::display-list-builder-scale :%impeller)
  (export '%impeller::display-list-builder-set-transform :%impeller)
  (export '%impeller::display-list-builder-transform :%impeller)
  (export '%impeller::display-list-builder-translate :%impeller)
  (export '%impeller::display-list-release :%impeller)
  (export '%impeller::display-list-retain :%impeller)
  (export '%impeller::mapping :%impeller)
  (export '%impeller::fragment-program-new :%impeller)
  (export '%impeller::fragment-program-release :%impeller)
  (export '%impeller::fragment-program-retain :%impeller)
  (export '%impeller::get-version :%impeller)
  (export '%impeller::glyph-info- :%impeller)
  (export '%impeller::glyph-info :%impeller)
  (export '%impeller::glyph-info-get-grapheme-cluster-bounds :%impeller)
  (export '%impeller::glyph-info-get-grapheme-cluster-code-unit-range-begin
          :%impeller)
  (export '%impeller::glyph-info-get-grapheme-cluster-code-unit-range-end
          :%impeller)
  (export '%impeller::glyph-info-get-text-direction :%impeller)
  (export '%impeller::glyph-info-is-ellipsis :%impeller)
  (export '%impeller::glyph-info-release :%impeller)
  (export '%impeller::glyph-info-retain :%impeller)
  (export '%impeller::image-filter-create-blur-new :%impeller)
  (export '%impeller::image-filter-create-compose-new :%impeller)
  (export '%impeller::image-filter-create-dilate-new :%impeller)
  (export '%impeller::image-filter-create-erode-new :%impeller)
  (export '%impeller::image-filter-create-fragment-program-new :%impeller)
  (export '%impeller::image-filter-create-matrix-new :%impeller)
  (export '%impeller::image-filter-release :%impeller)
  (export '%impeller::image-filter-retain :%impeller)
  (export '%impeller::line-metrics- :%impeller)
  (export '%impeller::line-metrics :%impeller)
  (export '%impeller::line-metrics-get-ascent :%impeller)
  (export '%impeller::line-metrics-get-baseline :%impeller)
  (export '%impeller::line-metrics-get-code-unit-end-index :%impeller)
  (export '%impeller::line-metrics-get-code-unit-end-index-excluding-whitespace
          :%impeller)
  (export '%impeller::line-metrics-get-code-unit-end-index-including-newline
          :%impeller)
  (export '%impeller::line-metrics-get-code-unit-start-index :%impeller)
  (export '%impeller::line-metrics-get-descent :%impeller)
  (export '%impeller::line-metrics-get-height :%impeller)
  (export '%impeller::line-metrics-get-left :%impeller)
  (export '%impeller::line-metrics-get-unscaled-ascent :%impeller)
  (export '%impeller::line-metrics-get-width :%impeller)
  (export '%impeller::line-metrics-is-hardbreak :%impeller)
  (export '%impeller::line-metrics-release :%impeller)
  (export '%impeller::line-metrics-retain :%impeller)
  (export '%impeller::mask-filter- :%impeller)
  (export '%impeller::mask-filter :%impeller)
  (export '%impeller::mask-filter-create-blur-new :%impeller)
  (export '%impeller::mask-filter-release :%impeller)
  (export '%impeller::mask-filter-retain :%impeller)
  (export '%impeller::paint-new :%impeller)
  (export '%impeller::paint-release :%impeller)
  (export '%impeller::paint-retain :%impeller)
  (export '%impeller::paint-set-blend-mode :%impeller)
  (export '%impeller::paint-set-color :%impeller)
  (export '%impeller::paint-set-color-filter :%impeller)
  (export '%impeller::paint-set-color-source :%impeller)
  (export '%impeller::paint-set-draw-style :%impeller)
  (export '%impeller::paint-set-image-filter :%impeller)
  (export '%impeller::paint-set-mask-filter :%impeller)
  (export '%impeller::paint-set-stroke-cap :%impeller)
  (export '%impeller::paint-set-stroke-join :%impeller)
  (export '%impeller::paint-set-stroke-miter :%impeller)
  (export '%impeller::paint-set-stroke-width :%impeller)
  (export '%impeller::paragraph-builder- :%impeller)
  (export '%impeller::paragraph-builder :%impeller)
  (export '%impeller::paragraph-builder-add-text :%impeller)
  (export '%impeller::paragraph-builder-build-paragraph-new :%impeller)
  (export '%impeller::typography-context- :%impeller)
  (export '%impeller::typography-context :%impeller)
  (export '%impeller::paragraph-builder-new :%impeller)
  (export '%impeller::paragraph-builder-pop-style :%impeller)
  (export '%impeller::paragraph-style- :%impeller)
  (export '%impeller::paragraph-style :%impeller)
  (export '%impeller::paragraph-builder-push-style :%impeller)
  (export '%impeller::paragraph-builder-release :%impeller)
  (export '%impeller::paragraph-builder-retain :%impeller)
  (export '%impeller::paragraph-create-glyph-info-at-code-unit-index-new
          :%impeller)
  (export '%impeller::paragraph-create-glyph-info-at-paragraph-coordinates-new
          :%impeller)
  (export '%impeller::paragraph-get-alphabetic-baseline :%impeller)
  (export '%impeller::paragraph-get-height :%impeller)
  (export '%impeller::paragraph-get-ideographic-baseline :%impeller)
  (export '%impeller::paragraph-get-line-count :%impeller)
  (export '%impeller::paragraph-get-line-metrics :%impeller)
  (export '%impeller::paragraph-get-longest-line-width :%impeller)
  (export '%impeller::paragraph-get-max-intrinsic-width :%impeller)
  (export '%impeller::paragraph-get-max-width :%impeller)
  (export '%impeller::paragraph-get-min-intrinsic-width :%impeller)
  (export '%impeller::range :%impeller)
  (export '%impeller::paragraph-get-word-boundary :%impeller)
  (export '%impeller::paragraph-release :%impeller)
  (export '%impeller::paragraph-retain :%impeller)
  (export '%impeller::paragraph-style-new :%impeller)
  (export '%impeller::paragraph-style-release :%impeller)
  (export '%impeller::paragraph-style-retain :%impeller)
  (export '%impeller::paragraph-style-set-background :%impeller)
  (export '%impeller::paragraph-style-set-ellipsis :%impeller)
  (export '%impeller::paragraph-style-set-font-family :%impeller)
  (export '%impeller::paragraph-style-set-font-size :%impeller)
  (export '%impeller::paragraph-style-set-font-style :%impeller)
  (export '%impeller::paragraph-style-set-font-weight :%impeller)
  (export '%impeller::paragraph-style-set-foreground :%impeller)
  (export '%impeller::paragraph-style-set-height :%impeller)
  (export '%impeller::paragraph-style-set-locale :%impeller)
  (export '%impeller::paragraph-style-set-max-lines :%impeller)
  (export '%impeller::paragraph-style-set-text-alignment :%impeller)
  (export '%impeller::text-decoration :%impeller)
  (export '%impeller::paragraph-style-set-text-decoration :%impeller)
  (export '%impeller::paragraph-style-set-text-direction :%impeller)
  (export '%impeller::path-builder- :%impeller)
  (export '%impeller::path-builder :%impeller)
  (export '%impeller::path-builder-add-arc :%impeller)
  (export '%impeller::path-builder-add-oval :%impeller)
  (export '%impeller::path-builder-add-rect :%impeller)
  (export '%impeller::path-builder-add-rounded-rect :%impeller)
  (export '%impeller::path-builder-close :%impeller)
  (export '%impeller::path-builder-copy-path-new :%impeller)
  (export '%impeller::path-builder-cubic-curve-to :%impeller)
  (export '%impeller::path-builder-line-to :%impeller)
  (export '%impeller::path-builder-move-to :%impeller)
  (export '%impeller::path-builder-new :%impeller)
  (export '%impeller::path-builder-quadratic-curve-to :%impeller)
  (export '%impeller::path-builder-release :%impeller)
  (export '%impeller::path-builder-retain :%impeller)
  (export '%impeller::path-builder-take-path-new :%impeller)
  (export '%impeller::path-get-bounds :%impeller)
  (export '%impeller::path-release :%impeller)
  (export '%impeller::path-retain :%impeller)
  (export '%impeller::surface- :%impeller)
  (export '%impeller::surface :%impeller)
  (export '%impeller::uint64-t :%impeller)
  (export '%impeller::i-size :%impeller)
  (export '%impeller::surface-create-wrapped-fbo-new :%impeller)
  (export '%impeller::surface-create-wrapped-metal-drawable-new :%impeller)
  (export '%impeller::surface-draw-display-list :%impeller)
  (export '%impeller::surface-present :%impeller)
  (export '%impeller::surface-release :%impeller)
  (export '%impeller::surface-retain :%impeller)
  (export '%impeller::texture-descriptor :%impeller)
  (export '%impeller::texture-create-with-contents-new :%impeller)
  (export '%impeller::texture-create-with-open-gl-texture-handle-new
          :%impeller)
  (export '%impeller::texture-get-open-gl-handle :%impeller)
  (export '%impeller::texture-release :%impeller)
  (export '%impeller::texture-retain :%impeller)
  (export '%impeller::typography-context-new :%impeller)
  (export '%impeller::typography-context-register-font :%impeller)
  (export '%impeller::typography-context-release :%impeller)
  (export '%impeller::typography-context-retain :%impeller)
  (export '%impeller::vulkan-swapchain- :%impeller)
  (export '%impeller::vulkan-swapchain :%impeller)
  (export '%impeller::vulkan-swapchain-acquire-next-surface-new :%impeller)
  (export '%impeller::vulkan-swapchain-create-new :%impeller)
  (export '%impeller::vulkan-swapchain-release :%impeller)
  (export '%impeller::vulkan-swapchain-retain :%impeller)
  (export '%impeller::size :%impeller)
  (export '%impeller::callback :%impeller)
  (export '%impeller::vulkan-proc-address-callback :%impeller))

