;; Generated by :claw at 2026-02-10T21:45:15.874210Z
(uiop:define-package :%flow (:use))
(uiop:define-package :flutter-render-stack-ffi-flow-bindings~pristine (:use :cl))
(common-lisp:in-package :flutter-render-stack-ffi-flow-bindings~pristine)

(defparameter %flow::+export+ nil)

(defparameter %flow::+export-decoration+ nil)

(defparameter %flow::+extern-c+ nil)

(defparameter %flow::+extern-c-begin+ nil)

(defparameter %flow::+nodiscard+ nil)

(defparameter %flow::+nonnull+ nil)

(defparameter %flow::+nullable+ nil)

(defparameter %flow::+version+ 536875008)

(defparameter %flow::+version-major+ 0)

(defparameter %flow::+version-minor+ 1)

(defparameter %flow::+version-patch+ 0)

(defparameter %flow::+version-variant+ 1)

(cffi:defcenum (%flow::clip-behavior :unsigned-int)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:253:9"
  (:anti-alias 0)
  (:hard-edge 1)
  (:none 2))

(cffi:defcenum (%flow::raster-status :unsigned-int)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:265:9"
  (:success 0)
  (:not-found 1)
  (:failed 2))

(cffi:defcstruct (%flow::clip-path-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:144:1")

(cffi:defctype %flow::clip-path-layer
               (claw-utils:claw-pointer (:struct %flow::clip-path-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:144:20")

(cffi:defcstruct (%flow::container-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:117:1")

(cffi:defctype %flow::container-layer
               (claw-utils:claw-pointer (:struct %flow::container-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:117:20")

(declaim (inline %flow::clip-path-layer-add-child))

(cffi:defcfun ("FlowClipPathLayerAddChild" %flow::clip-path-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:645:6"
  (%flow::parent %flow::clip-path-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::clip-path-layer-as-container))

(cffi:defcfun ("FlowClipPathLayerAsContainer"
               %flow::clip-path-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:649:1"
  (%flow::layer %flow::clip-path-layer))

(cffi:defctype %flow::clip-behavior %flow::clip-behavior
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:260:3")

(declaim (inline %flow::clip-path-layer-new))

(cffi:defcfun ("FlowClipPathLayerNew" %flow::clip-path-layer-new)
    %flow::clip-path-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:636:1"
  (%flow::clip-behavior %flow::clip-behavior))

(declaim (inline %flow::clip-path-layer-release))

(cffi:defcfun ("FlowClipPathLayerRelease" %flow::clip-path-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:642:6"
  (%flow::layer %flow::clip-path-layer))

(declaim (inline %flow::clip-path-layer-retain))

(cffi:defcfun ("FlowClipPathLayerRetain" %flow::clip-path-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:639:6"
  (%flow::layer %flow::clip-path-layer))

(cffi:defcstruct (%flow::clip-r-rect-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:139:1")

(cffi:defctype %flow::clip-r-rect-layer
               (claw-utils:claw-pointer (:struct %flow::clip-r-rect-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:139:20")

(declaim (inline %flow::clip-r-rect-layer-add-child))

(cffi:defcfun ("FlowClipRRectLayerAddChild" %flow::clip-r-rect-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:625:6"
  (%flow::parent %flow::clip-r-rect-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::clip-r-rect-layer-as-container))

(cffi:defcfun ("FlowClipRRectLayerAsContainer"
               %flow::clip-r-rect-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:629:1"
  (%flow::layer %flow::clip-r-rect-layer))

(cffi:defcstruct (%flow::rect :size 16)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:218:16"
  (%flow::x :float :offset 0)
  (%flow::y :float :offset 4)
  (%flow::width :float :offset 8)
  (%flow::height :float :offset 12))

(cffi:defctype %flow::rect (:struct %flow::rect)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:223:3")

(declaim (inline %flow::clip-r-rect-layer-new))

(cffi:defcfun ("FlowClipRRectLayerNew" %flow::clip-r-rect-layer-new)
    %flow::clip-r-rect-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:614:1"
  (%flow::bounds (claw-utils:claw-pointer %flow::rect))
  (%flow::corner-radius :float)
  (%flow::clip-behavior %flow::clip-behavior))

(declaim (inline %flow::clip-r-rect-layer-release))

(cffi:defcfun ("FlowClipRRectLayerRelease" %flow::clip-r-rect-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:622:6"
  (%flow::layer %flow::clip-r-rect-layer))

(declaim (inline %flow::clip-r-rect-layer-retain))

(cffi:defcfun ("FlowClipRRectLayerRetain" %flow::clip-r-rect-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:619:6"
  (%flow::layer %flow::clip-r-rect-layer))

(cffi:defcstruct (%flow::clip-rect-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:134:1")

(cffi:defctype %flow::clip-rect-layer
               (claw-utils:claw-pointer (:struct %flow::clip-rect-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:134:20")

(declaim (inline %flow::clip-rect-layer-add-child))

(cffi:defcfun ("FlowClipRectLayerAddChild" %flow::clip-rect-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:603:6"
  (%flow::parent %flow::clip-rect-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::clip-rect-layer-as-container))

(cffi:defcfun ("FlowClipRectLayerAsContainer"
               %flow::clip-rect-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:607:1"
  (%flow::layer %flow::clip-rect-layer))

(declaim (inline %flow::clip-rect-layer-new))

(cffi:defcfun ("FlowClipRectLayerNew" %flow::clip-rect-layer-new)
    %flow::clip-rect-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:593:1"
  (%flow::clip-rect (claw-utils:claw-pointer %flow::rect))
  (%flow::clip-behavior %flow::clip-behavior))

(declaim (inline %flow::clip-rect-layer-release))

(cffi:defcfun ("FlowClipRectLayerRelease" %flow::clip-rect-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:600:6"
  (%flow::layer %flow::clip-rect-layer))

(declaim (inline %flow::clip-rect-layer-retain))

(cffi:defcfun ("FlowClipRectLayerRetain" %flow::clip-rect-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:597:6"
  (%flow::layer %flow::clip-rect-layer))

(cffi:defcstruct (%flow::color-filter-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:154:1")

(cffi:defctype %flow::color-filter-layer
               (claw-utils:claw-pointer (:struct %flow::color-filter-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:154:20")

(declaim (inline %flow::color-filter-layer-add-child))

(cffi:defcfun ("FlowColorFilterLayerAddChild"
               %flow::color-filter-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:685:6"
  (%flow::parent %flow::color-filter-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::color-filter-layer-as-container))

(cffi:defcfun ("FlowColorFilterLayerAsContainer"
               %flow::color-filter-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:689:1"
  (%flow::layer %flow::color-filter-layer))

(declaim (inline %flow::color-filter-layer-new))

(cffi:defcfun ("FlowColorFilterLayerNew" %flow::color-filter-layer-new)
    %flow::color-filter-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:676:1"
  (%flow::color-filter (claw-utils:claw-pointer :void)))

(declaim (inline %flow::color-filter-layer-release))

(cffi:defcfun ("FlowColorFilterLayerRelease" %flow::color-filter-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:682:6"
  (%flow::layer %flow::color-filter-layer))

(declaim (inline %flow::color-filter-layer-retain))

(cffi:defcfun ("FlowColorFilterLayerRetain" %flow::color-filter-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:679:6"
  (%flow::layer %flow::color-filter-layer))

(cffi:defcstruct (%flow::scoped-frame- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:174:1")

(cffi:defctype %flow::scoped-frame
               (claw-utils:claw-pointer (:struct %flow::scoped-frame-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:174:20")

(cffi:defcstruct (%flow::compositor-context- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:166:1")

(cffi:defctype %flow::compositor-context
               (claw-utils:claw-pointer (:struct %flow::compositor-context-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:166:20")

(cffi:defcstruct (%flow::impeller-context- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:198:16")

(cffi:defctype %flow::impeller-context
               (claw-utils:claw-pointer (:struct %flow::impeller-context-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:198:34")

(cffi:defctype %flow::int32-t :int "/usr/include/bits/stdint-intn.h:26:19")

(cffi:defcstruct (%flow::i-size :size 8)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:206:16"
  (%flow::width %flow::int32-t :offset 0)
  (%flow::height %flow::int32-t :offset 4))

(cffi:defctype %flow::i-size (:struct %flow::i-size)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:209:3")

(declaim (inline %flow::compositor-context-acquire-frame))

(cffi:defcfun ("FlowCompositorContextAcquireFrame"
               %flow::compositor-context-acquire-frame)
    %flow::scoped-frame
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:778:1"
  (%flow::context %flow::compositor-context)
  (%flow::impeller-context %flow::impeller-context)
  (%flow::frame-size (claw-utils:claw-pointer %flow::i-size)))

(cffi:defcstruct (%flow::raster-cache- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:190:1")

(cffi:defctype %flow::raster-cache
               (claw-utils:claw-pointer (:struct %flow::raster-cache-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:190:20")

(declaim (inline %flow::compositor-context-get-raster-cache))

(cffi:defcfun ("FlowCompositorContextGetRasterCache"
               %flow::compositor-context-get-raster-cache)
    %flow::raster-cache
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:752:1"
  (%flow::context %flow::compositor-context))

(cffi:defctype %flow::uint32-t :unsigned-int
               "/usr/include/bits/stdint-uintn.h:26:20")

(declaim (inline %flow::compositor-context-new))

(cffi:defcfun ("FlowCompositorContextNew" %flow::compositor-context-new)
    %flow::compositor-context
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:723:1"
  (%flow::version %flow::uint32-t))

(declaim (inline %flow::compositor-context-release))

(cffi:defcfun ("FlowCompositorContextRelease" %flow::compositor-context-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:739:6"
  (%flow::context %flow::compositor-context))

(declaim (inline %flow::compositor-context-retain))

(cffi:defcfun ("FlowCompositorContextRetain" %flow::compositor-context-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:731:6"
  (%flow::context %flow::compositor-context))

(declaim (inline %flow::container-layer-release))

(cffi:defcfun ("FlowContainerLayerRelease" %flow::container-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:483:6"
  (%flow::layer %flow::container-layer))

(declaim (inline %flow::container-layer-retain))

(cffi:defcfun ("FlowContainerLayerRetain" %flow::container-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:475:6"
  (%flow::layer %flow::container-layer))

(cffi:defcstruct (%flow::display-list-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:124:1")

(cffi:defctype %flow::display-list-layer
               (claw-utils:claw-pointer (:struct %flow::display-list-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:124:20")

(declaim (inline %flow::display-list-layer-as-container))

(cffi:defcfun ("FlowDisplayListLayerAsContainer"
               %flow::display-list-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:577:1"
  (%flow::layer %flow::display-list-layer))

(cffi:defcstruct (%flow::point :size 8)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:225:16"
  (%flow::x :float :offset 0)
  (%flow::y :float :offset 4))

(cffi:defctype %flow::point (:struct %flow::point)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:228:3")

(declaim (inline %flow::display-list-layer-new))

(cffi:defcfun ("FlowDisplayListLayerNew" %flow::display-list-layer-new)
    %flow::display-list-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:550:1"
  (%flow::offset (claw-utils:claw-pointer %flow::point))
  (%flow::display-list (claw-utils:claw-pointer :void)))

(declaim (inline %flow::display-list-layer-release))

(cffi:defcfun ("FlowDisplayListLayerRelease" %flow::display-list-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:567:6"
  (%flow::layer %flow::display-list-layer))

(declaim (inline %flow::display-list-layer-retain))

(cffi:defcfun ("FlowDisplayListLayerRetain" %flow::display-list-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:559:6"
  (%flow::layer %flow::display-list-layer))

(cffi:defcstruct (%flow::frame-damage- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:182:1")

(cffi:defctype %flow::frame-damage
               (claw-utils:claw-pointer (:struct %flow::frame-damage-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:182:20")

(cffi:defcstruct (%flow::i-rect :size 16)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:211:16"
  (%flow::x %flow::int32-t :offset 0)
  (%flow::y %flow::int32-t :offset 4)
  (%flow::width %flow::int32-t :offset 8)
  (%flow::height %flow::int32-t :offset 12))

(cffi:defctype %flow::i-rect (:struct %flow::i-rect)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:216:3")

(declaim (inline %flow::frame-damage-add-additional-damage))

(cffi:defcfun ("FlowFrameDamageAddAdditionalDamage"
               %flow::frame-damage-add-additional-damage)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:1039:6"
  (%flow::damage %flow::frame-damage)
  (%flow::rect (claw-utils:claw-pointer %flow::i-rect)))

(cffi:defcstruct (%flow::layer-tree- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:110:1")

(cffi:defctype %flow::layer-tree
               (claw-utils:claw-pointer (:struct %flow::layer-tree-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:110:20")

(declaim (inline %flow::frame-damage-compute-clip-rect))

(cffi:defcfun ("FlowFrameDamageComputeClipRect"
               %flow::frame-damage-compute-clip-rect)
    :bool
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:1065:6"
  (%flow::damage %flow::frame-damage)
  (%flow::tree %flow::layer-tree)
  (%flow::out-clip-rect (claw-utils:claw-pointer %flow::i-rect)))

(declaim (inline %flow::frame-damage-new))

(cffi:defcfun ("FlowFrameDamageNew" %flow::frame-damage-new)
    %flow::frame-damage
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:985:1"
  (%flow::version %flow::uint32-t)
  (%flow::frame-size (claw-utils:claw-pointer %flow::i-size)))

(declaim (inline %flow::frame-damage-release))

(cffi:defcfun ("FlowFrameDamageRelease" %flow::frame-damage-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:1001:6"
  (%flow::damage %flow::frame-damage))

(declaim (inline %flow::frame-damage-retain))

(cffi:defcfun ("FlowFrameDamageRetain" %flow::frame-damage-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:993:6"
  (%flow::damage %flow::frame-damage))

(declaim (inline %flow::frame-damage-set-previous-layer-tree))

(cffi:defcfun ("FlowFrameDamageSetPreviousLayerTree"
               %flow::frame-damage-set-previous-layer-tree)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:1020:6"
  (%flow::damage %flow::frame-damage)
  (%flow::tree %flow::layer-tree))

(declaim (inline %flow::get-version))

(cffi:defcfun ("FlowGetVersion" %flow::get-version)
    %flow::uint32-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:94:10")

(cffi:defcstruct (%flow::image-filter-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:159:1")

(cffi:defctype %flow::image-filter-layer
               (claw-utils:claw-pointer (:struct %flow::image-filter-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:159:20")

(declaim (inline %flow::image-filter-layer-add-child))

(cffi:defcfun ("FlowImageFilterLayerAddChild"
               %flow::image-filter-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:705:6"
  (%flow::parent %flow::image-filter-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::image-filter-layer-as-container))

(cffi:defcfun ("FlowImageFilterLayerAsContainer"
               %flow::image-filter-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:709:1"
  (%flow::layer %flow::image-filter-layer))

(declaim (inline %flow::image-filter-layer-new))

(cffi:defcfun ("FlowImageFilterLayerNew" %flow::image-filter-layer-new)
    %flow::image-filter-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:696:1"
  (%flow::image-filter (claw-utils:claw-pointer :void)))

(declaim (inline %flow::image-filter-layer-release))

(cffi:defcfun ("FlowImageFilterLayerRelease" %flow::image-filter-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:702:6"
  (%flow::layer %flow::image-filter-layer))

(declaim (inline %flow::image-filter-layer-retain))

(cffi:defcfun ("FlowImageFilterLayerRetain" %flow::image-filter-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:699:6"
  (%flow::layer %flow::image-filter-layer))

(declaim (inline %flow::layer-tree-get-frame-size))

(cffi:defcfun ("FlowLayerTreeGetFrameSize" %flow::layer-tree-get-frame-size)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:462:6"
  (%flow::tree %flow::layer-tree)
  (%flow::out-size (claw-utils:claw-pointer %flow::i-size)))

(declaim (inline %flow::layer-tree-new))

(cffi:defcfun ("FlowLayerTreeNew" %flow::layer-tree-new)
    %flow::layer-tree
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:427:1"
  (%flow::version %flow::uint32-t)
  (%flow::frame-size (claw-utils:claw-pointer %flow::i-size)))

(declaim (inline %flow::layer-tree-release))

(cffi:defcfun ("FlowLayerTreeRelease" %flow::layer-tree-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:443:6"
  (%flow::tree %flow::layer-tree))

(declaim (inline %flow::layer-tree-retain))

(cffi:defcfun ("FlowLayerTreeRetain" %flow::layer-tree-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:435:6"
  (%flow::tree %flow::layer-tree))

(declaim (inline %flow::layer-tree-set-root-layer))

(cffi:defcfun ("FlowLayerTreeSetRootLayer" %flow::layer-tree-set-root-layer)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:452:6"
  (%flow::tree %flow::layer-tree)
  (%flow::layer %flow::container-layer))

(cffi:defcstruct (%flow::matrix :size 64)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:230:16"
  (%flow::m :float :count 16 :offset 0))

(cffi:defctype %flow::matrix (:struct %flow::matrix)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:232:3")

(declaim (inline %flow::matrix-invert))

(cffi:defcfun ("FlowMatrixInvert" %flow::matrix-invert)
    :bool
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:388:6"
  (%flow::matrix (claw-utils:claw-pointer %flow::matrix))
  (%flow::out-inverted (claw-utils:claw-pointer %flow::matrix)))

(declaim (inline %flow::matrix-multiply))

(cffi:defcfun ("FlowMatrixMultiply" %flow::matrix-multiply)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:410:6"
  (%flow::a (claw-utils:claw-pointer %flow::matrix))
  (%flow::b (claw-utils:claw-pointer %flow::matrix))
  (%flow::out-result (claw-utils:claw-pointer %flow::matrix)))

(cffi:defcstruct (%flow::opacity-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:149:1")

(cffi:defctype %flow::opacity-layer
               (claw-utils:claw-pointer (:struct %flow::opacity-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:149:20")

(declaim (inline %flow::opacity-layer-add-child))

(cffi:defcfun ("FlowOpacityLayerAddChild" %flow::opacity-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:665:6"
  (%flow::parent %flow::opacity-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::opacity-layer-as-container))

(cffi:defcfun ("FlowOpacityLayerAsContainer" %flow::opacity-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:669:1"
  (%flow::layer %flow::opacity-layer))

(declaim (inline %flow::opacity-layer-new))

(cffi:defcfun ("FlowOpacityLayerNew" %flow::opacity-layer-new)
    %flow::opacity-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:656:1"
  (%flow::alpha :int)
  (%flow::offset (claw-utils:claw-pointer %flow::point)))

(declaim (inline %flow::opacity-layer-release))

(cffi:defcfun ("FlowOpacityLayerRelease" %flow::opacity-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:662:6"
  (%flow::layer %flow::opacity-layer))

(declaim (inline %flow::opacity-layer-retain))

(cffi:defcfun ("FlowOpacityLayerRetain" %flow::opacity-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:659:6"
  (%flow::layer %flow::opacity-layer))

(declaim (inline %flow::point-transform))

(cffi:defcfun ("FlowPointTransform" %flow::point-transform)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:366:6"
  (%flow::point (claw-utils:claw-pointer %flow::point))
  (%flow::matrix (claw-utils:claw-pointer %flow::matrix))
  (%flow::out-point (claw-utils:claw-pointer %flow::point)))

(declaim (inline %flow::raster-cache-clear))

(cffi:defcfun ("FlowRasterCacheClear" %flow::raster-cache-clear)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:872:6"
  (%flow::cache %flow::raster-cache))

(cffi:defctype %flow::size-t :unsigned-long
               "/usr/lib64/clang/21/include/__stddef_size_t.h:18:23")

(declaim (inline %flow::raster-cache-estimate-layer-byte-size))

(cffi:defcfun ("FlowRasterCacheEstimateLayerByteSize"
               %flow::raster-cache-estimate-layer-byte-size)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:960:8"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-estimate-picture-byte-size))

(cffi:defcfun ("FlowRasterCacheEstimatePictureByteSize"
               %flow::raster-cache-estimate-picture-byte-size)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:949:8"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-get-access-threshold))

(cffi:defcfun ("FlowRasterCacheGetAccessThreshold"
               %flow::raster-cache-get-access-threshold)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:885:8"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-get-cached-entries-count))

(cffi:defcfun ("FlowRasterCacheGetCachedEntriesCount"
               %flow::raster-cache-get-cached-entries-count)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:917:8"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-get-layer-cached-entries-count))

(cffi:defcfun ("FlowRasterCacheGetLayerCachedEntriesCount"
               %flow::raster-cache-get-layer-cached-entries-count)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:927:8"
  (%flow::cache %flow::raster-cache))

(cffi:defcstruct (%flow::raster-cache-metrics :size 32)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:239:16"
  (%flow::eviction-count %flow::size-t :offset 0)
  (%flow::eviction-bytes %flow::size-t :offset 8)
  (%flow::in-use-count %flow::size-t :offset 16)
  (%flow::in-use-bytes %flow::size-t :offset 24))

(cffi:defctype %flow::raster-cache-metrics
               (:struct %flow::raster-cache-metrics)
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:248:3")

(declaim (inline %flow::raster-cache-get-layer-metrics))

(cffi:defcfun ("FlowRasterCacheGetLayerMetrics"
               %flow::raster-cache-get-layer-metrics)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:905:6"
  (%flow::cache %flow::raster-cache)
  (%flow::out-metrics (claw-utils:claw-pointer %flow::raster-cache-metrics)))

(declaim (inline %flow::raster-cache-get-picture-cached-entries-count))

(cffi:defcfun ("FlowRasterCacheGetPictureCachedEntriesCount"
               %flow::raster-cache-get-picture-cached-entries-count)
    %flow::size-t
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:938:8"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-get-picture-metrics))

(cffi:defcfun ("FlowRasterCacheGetPictureMetrics"
               %flow::raster-cache-get-picture-metrics)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:894:6"
  (%flow::cache %flow::raster-cache)
  (%flow::out-metrics (claw-utils:claw-pointer %flow::raster-cache-metrics)))

(declaim (inline %flow::raster-cache-release))

(cffi:defcfun ("FlowRasterCacheRelease" %flow::raster-cache-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:864:6"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::raster-cache-retain))

(cffi:defcfun ("FlowRasterCacheRetain" %flow::raster-cache-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:856:6"
  (%flow::cache %flow::raster-cache))

(declaim (inline %flow::rect-contains-point))

(cffi:defcfun ("FlowRectContainsPoint" %flow::rect-contains-point)
    :bool
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:343:6"
  (%flow::rect (claw-utils:claw-pointer %flow::rect))
  (%flow::point (claw-utils:claw-pointer %flow::point)))

(declaim (inline %flow::rect-intersection))

(cffi:defcfun ("FlowRectIntersection" %flow::rect-intersection)
    :bool
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:299:6"
  (%flow::rect1 (claw-utils:claw-pointer %flow::rect))
  (%flow::rect2 (claw-utils:claw-pointer %flow::rect))
  (%flow::out-rect (claw-utils:claw-pointer %flow::rect)))

(declaim (inline %flow::rect-union))

(cffi:defcfun ("FlowRectUnion" %flow::rect-union)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:321:6"
  (%flow::rect1 (claw-utils:claw-pointer %flow::rect))
  (%flow::rect2 (claw-utils:claw-pointer %flow::rect))
  (%flow::out-rect (claw-utils:claw-pointer %flow::rect)))

(cffi:defcstruct (%flow::impeller-display-list- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:199:16")

(cffi:defctype %flow::impeller-display-list
               (claw-utils:claw-pointer
                (:struct %flow::impeller-display-list-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:199:38")

(declaim (inline %flow::scoped-frame-build-display-list-new))

(cffi:defcfun ("FlowScopedFrameBuildDisplayListNew"
               %flow::scoped-frame-build-display-list-new)
    %flow::impeller-display-list
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:828:1"
  (%flow::frame %flow::scoped-frame))

(cffi:defctype %flow::raster-status %flow::raster-status
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:272:3")

(declaim (inline %flow::scoped-frame-raster))

(cffi:defcfun ("FlowScopedFrameRaster" %flow::scoped-frame-raster)
    %flow::raster-status
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:803:18"
  (%flow::frame %flow::scoped-frame)
  (%flow::layer-tree %flow::layer-tree)
  (%flow::frame-damage %flow::frame-damage)
  (%flow::ignore-raster-cache :bool))

(declaim (inline %flow::scoped-frame-release))

(cffi:defcfun ("FlowScopedFrameRelease" %flow::scoped-frame-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:844:6"
  (%flow::frame %flow::scoped-frame))

(declaim (inline %flow::scoped-frame-retain))

(cffi:defcfun ("FlowScopedFrameRetain" %flow::scoped-frame-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:836:6"
  (%flow::frame %flow::scoped-frame))

(cffi:defcstruct (%flow::transform-layer- :size 0)
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:129:1")

(cffi:defctype %flow::transform-layer
               (claw-utils:claw-pointer (:struct %flow::transform-layer-))
               "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:129:20")

(declaim (inline %flow::transform-layer-add-child))

(cffi:defcfun ("FlowTransformLayerAddChild" %flow::transform-layer-add-child)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:522:6"
  (%flow::parent %flow::transform-layer)
  (%flow::child %flow::container-layer))

(declaim (inline %flow::transform-layer-as-container))

(cffi:defcfun ("FlowTransformLayerAsContainer"
               %flow::transform-layer-as-container)
    %flow::container-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:533:1"
  (%flow::layer %flow::transform-layer))

(declaim (inline %flow::transform-layer-new))

(cffi:defcfun ("FlowTransformLayerNew" %flow::transform-layer-new)
    %flow::transform-layer
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:497:1"
  (%flow::matrix (claw-utils:claw-pointer %flow::matrix)))

(declaim (inline %flow::transform-layer-release))

(cffi:defcfun ("FlowTransformLayerRelease" %flow::transform-layer-release)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:513:6"
  (%flow::layer %flow::transform-layer))

(declaim (inline %flow::transform-layer-retain))

(cffi:defcfun ("FlowTransformLayerRetain" %flow::transform-layer-retain)
    :void
  "/home/jboehland/work/render-stack-meta/repos/flutter-render-stack-ffi/src/flow/lib/flow.h:505:6"
  (%flow::layer %flow::transform-layer))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%flow::+export+ :%flow)
  (export '%flow::+export-decoration+ :%flow)
  (export '%flow::+extern-c+ :%flow)
  (export '%flow::+extern-c-begin+ :%flow)
  (export '%flow::+nodiscard+ :%flow)
  (export '%flow::+nonnull+ :%flow)
  (export '%flow::+nullable+ :%flow)
  (export '%flow::+version+ :%flow)
  (export '%flow::+version-major+ :%flow)
  (export '%flow::+version-minor+ :%flow)
  (export '%flow::+version-patch+ :%flow)
  (export '%flow::+version-variant+ :%flow)
  (export '%flow::clip-behavior :%flow)
  (export '%flow::raster-status :%flow)
  (export '%flow::clip-path-layer- :%flow)
  (export '%flow::clip-path-layer :%flow)
  (export '%flow::container-layer- :%flow)
  (export '%flow::container-layer :%flow)
  (export '%flow::clip-path-layer-add-child :%flow)
  (export '%flow::clip-path-layer-as-container :%flow)
  (export '%flow::clip-path-layer-new :%flow)
  (export '%flow::clip-path-layer-release :%flow)
  (export '%flow::clip-path-layer-retain :%flow)
  (export '%flow::clip-r-rect-layer- :%flow)
  (export '%flow::clip-r-rect-layer :%flow)
  (export '%flow::clip-r-rect-layer-add-child :%flow)
  (export '%flow::clip-r-rect-layer-as-container :%flow)
  (export '%flow::x :%flow)
  (export '%flow::y :%flow)
  (export '%flow::width :%flow)
  (export '%flow::height :%flow)
  (export '%flow::rect :%flow)
  (export '%flow::clip-r-rect-layer-new :%flow)
  (export '%flow::clip-r-rect-layer-release :%flow)
  (export '%flow::clip-r-rect-layer-retain :%flow)
  (export '%flow::clip-rect-layer- :%flow)
  (export '%flow::clip-rect-layer :%flow)
  (export '%flow::clip-rect-layer-add-child :%flow)
  (export '%flow::clip-rect-layer-as-container :%flow)
  (export '%flow::clip-rect-layer-new :%flow)
  (export '%flow::clip-rect-layer-release :%flow)
  (export '%flow::clip-rect-layer-retain :%flow)
  (export '%flow::color-filter-layer- :%flow)
  (export '%flow::color-filter-layer :%flow)
  (export '%flow::color-filter-layer-add-child :%flow)
  (export '%flow::color-filter-layer-as-container :%flow)
  (export '%flow::color-filter-layer-new :%flow)
  (export '%flow::color-filter-layer-release :%flow)
  (export '%flow::color-filter-layer-retain :%flow)
  (export '%flow::scoped-frame- :%flow)
  (export '%flow::scoped-frame :%flow)
  (export '%flow::compositor-context- :%flow)
  (export '%flow::compositor-context :%flow)
  (export '%flow::impeller-context- :%flow)
  (export '%flow::impeller-context :%flow)
  (export '%flow::int32-t :%flow)
  (export '%flow::i-size :%flow)
  (export '%flow::compositor-context-acquire-frame :%flow)
  (export '%flow::raster-cache- :%flow)
  (export '%flow::raster-cache :%flow)
  (export '%flow::compositor-context-get-raster-cache :%flow)
  (export '%flow::uint32-t :%flow)
  (export '%flow::compositor-context-new :%flow)
  (export '%flow::compositor-context-release :%flow)
  (export '%flow::compositor-context-retain :%flow)
  (export '%flow::container-layer-release :%flow)
  (export '%flow::container-layer-retain :%flow)
  (export '%flow::display-list-layer- :%flow)
  (export '%flow::display-list-layer :%flow)
  (export '%flow::display-list-layer-as-container :%flow)
  (export '%flow::point :%flow)
  (export '%flow::display-list-layer-new :%flow)
  (export '%flow::display-list-layer-release :%flow)
  (export '%flow::display-list-layer-retain :%flow)
  (export '%flow::frame-damage- :%flow)
  (export '%flow::frame-damage :%flow)
  (export '%flow::i-rect :%flow)
  (export '%flow::frame-damage-add-additional-damage :%flow)
  (export '%flow::layer-tree- :%flow)
  (export '%flow::layer-tree :%flow)
  (export '%flow::frame-damage-compute-clip-rect :%flow)
  (export '%flow::frame-damage-new :%flow)
  (export '%flow::frame-damage-release :%flow)
  (export '%flow::frame-damage-retain :%flow)
  (export '%flow::frame-damage-set-previous-layer-tree :%flow)
  (export '%flow::get-version :%flow)
  (export '%flow::image-filter-layer- :%flow)
  (export '%flow::image-filter-layer :%flow)
  (export '%flow::image-filter-layer-add-child :%flow)
  (export '%flow::image-filter-layer-as-container :%flow)
  (export '%flow::image-filter-layer-new :%flow)
  (export '%flow::image-filter-layer-release :%flow)
  (export '%flow::image-filter-layer-retain :%flow)
  (export '%flow::layer-tree-get-frame-size :%flow)
  (export '%flow::layer-tree-new :%flow)
  (export '%flow::layer-tree-release :%flow)
  (export '%flow::layer-tree-retain :%flow)
  (export '%flow::layer-tree-set-root-layer :%flow)
  (export '%flow::m :%flow)
  (export '%flow::matrix :%flow)
  (export '%flow::matrix-invert :%flow)
  (export '%flow::matrix-multiply :%flow)
  (export '%flow::opacity-layer- :%flow)
  (export '%flow::opacity-layer :%flow)
  (export '%flow::opacity-layer-add-child :%flow)
  (export '%flow::opacity-layer-as-container :%flow)
  (export '%flow::opacity-layer-new :%flow)
  (export '%flow::opacity-layer-release :%flow)
  (export '%flow::opacity-layer-retain :%flow)
  (export '%flow::point-transform :%flow)
  (export '%flow::raster-cache-clear :%flow)
  (export '%flow::size-t :%flow)
  (export '%flow::raster-cache-estimate-layer-byte-size :%flow)
  (export '%flow::raster-cache-estimate-picture-byte-size :%flow)
  (export '%flow::raster-cache-get-access-threshold :%flow)
  (export '%flow::raster-cache-get-cached-entries-count :%flow)
  (export '%flow::raster-cache-get-layer-cached-entries-count :%flow)
  (export '%flow::eviction-count :%flow)
  (export '%flow::eviction-bytes :%flow)
  (export '%flow::in-use-count :%flow)
  (export '%flow::in-use-bytes :%flow)
  (export '%flow::raster-cache-metrics :%flow)
  (export '%flow::raster-cache-get-layer-metrics :%flow)
  (export '%flow::raster-cache-get-picture-cached-entries-count :%flow)
  (export '%flow::raster-cache-get-picture-metrics :%flow)
  (export '%flow::raster-cache-release :%flow)
  (export '%flow::raster-cache-retain :%flow)
  (export '%flow::rect-contains-point :%flow)
  (export '%flow::rect-intersection :%flow)
  (export '%flow::rect-union :%flow)
  (export '%flow::impeller-display-list- :%flow)
  (export '%flow::impeller-display-list :%flow)
  (export '%flow::scoped-frame-build-display-list-new :%flow)
  (export '%flow::scoped-frame-raster :%flow)
  (export '%flow::scoped-frame-release :%flow)
  (export '%flow::scoped-frame-retain :%flow)
  (export '%flow::transform-layer- :%flow)
  (export '%flow::transform-layer :%flow)
  (export '%flow::transform-layer-add-child :%flow)
  (export '%flow::transform-layer-as-container :%flow)
  (export '%flow::transform-layer-new :%flow)
  (export '%flow::transform-layer-release :%flow)
  (export '%flow::transform-layer-retain :%flow))

